# -*- coding: utf-8 -*-
# Recherchierte Leads: Umzugsfirmen Kanton Bern
# Felder: name, vn, nn, pos, ort, adresse, tel, teldirekt, mail, web, qentscheider, qkontakt,
#         services, ws, schwaechen, chance, paket, preis, agents, agentbegr, upsell, reputation, aufhaenger,
#         b_web, b_pot, b_err, b_ag
L = []
def add(**k): L.append(k)

add(name="HUMAIR GmbH (Humair Umzüge & Transporte)", vn="Karin Monica", nn="Arter-Humair", pos="Gesellschafterin & Geschäftsführerin",
    ort="Biel/Bienne", adresse="Chemin de la Pierre-aux-Sarrasins 6, 2504 Biel/Bienne (HR-Sitz: Heidensteinweg 6, 2504 Biel)",
    tel="032 341 45 35", teldirekt="Nicht gefunden", mail="container@humair.gmbh", web="https://www.humair.gmbh",
    qentscheider="Handelsregister BE / Moneyhouse (UID CHE-297.293.396), zusätzlich Thomas Arter als GF eingetragen",
    qkontakt="Firmenwebsite humair.gmbh, search.ch, local.ch",
    services="Umzüge, Transporte, Möbellift bis 29 m, Kranarbeiten, Containerlogistik, Möbeleinlagerung",
    ws=1,
    schwaechen="Zahlreiche kaputte Bildreferenzen auf der Startseite; doppelte Inhaltsblöcke; unverständlicher gemischter DE/FR-Textblock; keine vollständige Firmenadresse auf der Website; veraltete HTML-Struktur ohne erkennbares Responsive-Layout",
    chance="Traditionsbetrieb seit 1955 mit teurer Spezialausrüstung (Möbellift 29 m, Kran), dessen Website den Wert dieser Leistungen praktisch unsichtbar macht.",
    paket="Website Business", preis=2790,
    agents="SEO; Funnel; Google-Bewertungen-AI-Agent",
    agentbegr="SEO – hohe Relevanz, da die Website technisch und inhaltlich kaum auffindbar strukturiert ist und lokale Sichtbarkeit für 'Umzugsfirma Biel' fehlt. Funnel – kein Offertenprozess vorhanden, Anfragen laufen nur über eine E-Mail-Verfügbarkeitsanfrage. Google-Bewertungen-AI-Agent – Betrieb seit 1955 mit Google-Eintrag, Reputation wird online nicht bewirtschaftet.",
    upsell=1, reputation="Google-Business-Eintrag über local.ch/search.ch vorhanden; auf der Website werden keinerlei Bewertungen oder Referenzen gezeigt.",
    aufhaenger="Auf Ihrer Website laden mehrere Bilder nicht und ein Textblock vermischt Deutsch und Französisch – Ihr Möbellift bis 29 Meter kommt dadurch online gar nicht zur Geltung.",
    b_web=4, b_pot=3, b_err=1, b_ag=1)

add(name="PUR Pack Umzüge und Reinigungen", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Worb / Uetendorf", adresse="Enggisteinstrasse 77, 3076 Worb (Zweitstandort: Industriestrasse 12, 3661 Uetendorf)",
    tel="031 954 26 90", teldirekt="079 840 05 82 (Mobilnummer des Betriebs, öffentlich in Verzeichnissen)", mail="info@p-u-r.ch", web="https://www.p-u-r.ch",
    qentscheider="Nicht gefunden – kein Handelsregistereintrag mit Personendaten öffentlich auffindbar",
    qkontakt="search.ch (Worb/Uetendorf), branchenbuch.ch",
    services="Umzüge, Transporte, Räumungen, Entsorgung, Umzugs- und Wohnungsreinigung",
    ws=1,
    schwaechen="Die Website liefert reproduzierbar HTTP 500 (Internal Server Error) und ist damit für Kunden nicht aufrufbar; kein einziger Inhalt erreichbar; keine Offertenmöglichkeit; das Unternehmen ist online faktisch nur über Verzeichniseinträge sichtbar",
    chance="Das Unternehmen ist in Verzeichnissen aktiv gelistet und hat zwei Standorte, verliert aber jede Website-Anfrage, weil die Domain einen Serverfehler ausgibt.",
    paket="Website Business", preis=2790,
    agents="Funnel; SEO",
    agentbegr="Funnel – ohne funktionierende Website existiert derzeit überhaupt keine Anfragestrecke; ein sauberer Offertenprozess ist der schnellste Hebel. SEO – nach dem Neuaufbau muss die lokale Sichtbarkeit für Worb, Uetendorf und Thun neu aufgebaut werden.",
    upsell=1, reputation="Nicht gefunden – keine Bewertungen über die Website verifizierbar, da die Seite nicht lädt.",
    aufhaenger="Ihre Website p-u-r.ch gibt aktuell einen Serverfehler aus und lässt sich gar nicht öffnen – jede Anfrage, die dort landet, ist verloren.",
    b_web=4, b_pot=3, b_err=1, b_ag=1)

add(name="DILARA SWISS AG", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Ittigen", adresse="Worblentalstrasse 30, 3063 Ittigen",
    tel="0848 600 500", teldirekt="Nicht gefunden", mail="info@dilaraswiss.ch", web="https://dilaraswiss.ch",
    qentscheider="Nicht gefunden – im öffentlich einsehbaren Umfang keine Personendaten zuordenbar",
    qkontakt="search.ch, local.ch, hellopage.ch",
    services="Umzüge, Transporte, Möbellagerung, Wohnungs- und Gebäudereinigung, Umzugsreinigung, Fassadenreinigung",
    ws=1,
    schwaechen="Die Domain ist nicht erreichbar (Verbindungsabbruch beim Verbindungsaufbau, wiederholt geprüft); dadurch keinerlei Online-Präsentation der Leistungen; Interessenten finden nur Verzeichniseinträge; keine Offerten- oder Kontaktstrecke online nutzbar",
    chance="Als AG mit breitem Leistungsportfolio (Umzug, Transport, Lagerung, Reinigung) fehlt jede digitale Verkaufsfläche.",
    paket="Website Business", preis=2790,
    agents="Funnel; SEO; Google-Bewertungen-AI-Agent",
    agentbegr="Funnel – es existiert aktuell keine erreichbare Anfragestrecke. SEO – lokale Sichtbarkeit für Ittigen/Bern muss vollständig neu aufgebaut werden. Google-Bewertungen-AI-Agent – das Unternehmen ist auf mehreren Bewertungsportalen gelistet, ohne dass die Reputation gepflegt wird.",
    upsell=1, reputation="In mehreren Verzeichnissen (local.ch, cleanify.ch, Yelp) gelistet; Bewertungsstand nicht über eigene Website belegt.",
    aufhaenger="Ihre Domain dilaraswiss.ch antwortet aktuell nicht – Kunden, die Sie über Verzeichnisse finden, landen ins Leere.",
    b_web=4, b_pot=3, b_err=1, b_ag=1)

add(name="Simsek Liegenschaftsdienste & Umzüge GmbH", vn="Sibel", nn="Simsek", pos="Geschäftsführerin",
    ort="Ostermundigen", adresse="Mitteldorfstrasse 49, 3072 Ostermundigen",
    tel="077 212 60 16", teldirekt="077 212 60 16 (Mobilnummer, als Firmenkontakt publiziert)", mail="Nicht gefunden", web="https://www.simsek.gmbh",
    qentscheider="Handelsregister BE / Moneyhouse (UID CHE-222.385.531), Gründung 2024",
    qkontakt="search.ch, moneyhouse.ch",
    services="Umzüge, Liegenschaftsdienste, Reinigung, Hauswartung, Renovation, Gartenarbeiten",
    ws=2,
    schwaechen="Die Website liefert HTTP 526 – das SSL-Zertifikat der Ursprungsserver ist ungültig, Besucher erhalten eine Sicherheitswarnung statt der Seite; keine gültige HTTPS-Verbindung; dadurch weder Leistungsdarstellung noch Offertenformular nutzbar; keine E-Mail-Adresse öffentlich auffindbar",
    chance="Junges Unternehmen mit Umzügen als eingetragenem Zweck, das mit einer sicheren, funktionierenden Website sofort Anfragen abholen könnte.",
    paket="Website Essential", preis=1790,
    agents="Funnel; SEO; Insta-Agent",
    agentbegr="Funnel – es fehlt eine funktionsfähige Anfragestrecke komplett. SEO – als Neugründung 2024 ist lokale Auffindbarkeit in Ostermundigen/Bern der wichtigste Wachstumshebel. Insta-Agent – das Unternehmen betreibt bereits ein Instagram-Profil (simsek.gmbh), das systematisch bespielt werden könnte.",
    upsell=1, reputation="Instagram-Profil vorhanden; Google-Bewertungen nicht verifizierbar.",
    aufhaenger="Ihre Seite simsek.gmbh zeigt Besuchern derzeit eine SSL-Sicherheitswarnung statt Ihrer Leistungen – das kostet gerade bei Neukunden sofort Vertrauen.",
    b_web=4, b_pot=2, b_err=2, b_ag=1)

add(name="E&T Umzüge und Räumungen", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Bern (Betriebssitz Mühlethurnen/Gürbetal)", adresse="Jupiterstrasse 57, 3015 Bern",
    tel="079 222 61 63", teldirekt="079 222 61 63 (Mobilnummer, als Hauptkontakt publiziert)", mail="info@et-umzuege.ch", web="https://et-umzuege.ch",
    qentscheider="Nicht gefunden – auf der Website wird keine verantwortliche Person genannt, kein Impressum mit Personendaten",
    qkontakt="Firmenwebsite et-umzuege.ch, search.ch, local.ch",
    services="Privatumzüge, Büroumzüge, Räumungen, Entsorgungen",
    ws=2,
    schwaechen="Optisch veraltetes Layout im Stil früher 2000er-Jahre; keine vollständige Firmenadresse auf der Website; kein Inhaber/Verantwortlicher genannt (kein vollständiges Impressum); keine Kundenbewertungen oder Referenzen; generisches Platzhalter-Teamfoto",
    chance="Seit 2002 am Markt und mit klarem Leistungsprofil, wirkt online aber wie ein Kleinstanbieter – eine seriöse Website würde die Preisdurchsetzung deutlich verbessern.",
    paket="Website Essential", preis=1790,
    agents="Funnel; SEO; Google-Bewertungen-AI-Agent",
    agentbegr="Funnel – der 'Offerte anfordern'-Button führt nicht in eine strukturierte Anfragestrecke, Conversion bleibt Zufall. SEO – veraltete Struktur und dünne Texte verschenken lokale Sichtbarkeit für 'Umzugsfirma Bern'. Google-Bewertungen-AI-Agent – über 20 Jahre Kundenkontakt, aber keinerlei sichtbare Bewertungen.",
    upsell=1, reputation="Keine Bewertungen auf der Website eingebunden; Facebook-Verlinkung vorhanden.",
    aufhaenger="Ihre Website wirkt optisch wie aus den frühen 2000ern und zeigt weder eine Adresse noch eine verantwortliche Person – bei über 20 Jahren Erfahrung ist das schade.",
    b_web=4, b_pot=2, b_err=1, b_ag=1)

add(name="Mascho Transport GmbH (Mascho Umzüge)", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Ostermundigen", adresse="Bernstrasse 135, 3072 Ostermundigen",
    tel="079 535 65 61", teldirekt="079 535 65 61 (Mobilnummer, als Firmenkontakt publiziert)", mail="Nicht gefunden", web="https://mascho-transport.ch",
    qentscheider="Nicht gefunden – auf der Website keine Personenangabe, kein vollständiges Impressum",
    qkontakt="search.ch, local.ch",
    services="Privatumzüge, Geschäfts-/Büroumzüge, Ferntransporte, Möbellagerung, Möbelmontage",
    ws=2,
    schwaechen="Als Adresse steht der Platzhalter 'Beispielstrasse 12, 3011 Bern' auf der Seite; auf der Website ist weder eine Telefonnummer noch eine E-Mail-Adresse hinterlegt; kein funktionierendes Offertenformular trotz Aufforderung zur Offertenanfrage; einfaches WordPress-Standardtheme mit Emoji-Überfrachtung; inkonsistente Firmierung (Mascho Transport / Mascho Umzüge); interner Link auf eine Lausanne-Seite deutet auf ungenutzte Template-Reste hin",
    chance="Seit 2009 aktiv, aber die Website nennt weder Telefon noch echte Adresse – jede Online-Anfrage geht verloren.",
    paket="Website Essential", preis=1790,
    agents="Funnel; SEO",
    agentbegr="Funnel – ohne Kontaktdaten und ohne Formular gibt es online null Conversion-Möglichkeit. SEO – die Seite ist inhaltlich dünn und mit Template-Resten belastet, lokale Rankings für Ostermundigen/Bern sind nicht abgeholt.",
    upsell=1, reputation="Nicht gefunden – keine Bewertungen auf der Website; Verzeichniseinträge vorhanden.",
    aufhaenger="Auf Ihrer Website steht als Adresse noch 'Beispielstrasse 12' und es ist weder Ihre Telefonnummer noch eine E-Mail hinterlegt – Interessenten können Sie über die Seite gar nicht erreichen.",
    b_web=4, b_pot=2, b_err=1, b_ag=1)

add(name="reist & witschi Umzüge (Reist-Witschi Umzüge, Transporte, Einlagerungen)", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Gutenburg (Gemeinde Madiswil)", adresse="Badstrasse 4, 4932 Gutenburg",
    tel="062 922 00 44", teldirekt="Nicht gefunden", mail="info@reistwitschi-umzuege.ch", web="https://www.reistwitschi-umzuege.ch",
    qentscheider="Nicht gefunden – Website nennt keine verantwortliche Person; kein Handelsregistereintrag mit Personendaten auffindbar",
    qkontakt="Firmenwebsite reistwitschi-umzuege.ch, search.ch, local.ch",
    services="Privat- und Geschäftsumzüge, Möbeltransporte schweizweit, Klavier-/Flügel-/Tresortransporte, Räumungen, Möbeleinlagerung (kurz/mittel/lang)",
    ws=2,
    schwaechen="Generische Wix-Vorlage ohne eigenständiges Erscheinungsbild; kein Offerten- oder Kontaktformular auf der Startseite; der Menüpunkt 'Kundenrückmeldungen' führt zu keiner sichtbaren Bewertung; keine Copyright-/Aktualitätsangabe; Überschriften mit Keyword-Aneinanderreihungen statt echter Verkaufstexte; erkennbar schwache mobile Darstellung",
    chance="Spezialleistungen wie Klavier-, Flügel- und Tresortransporte sowie Möbellagerung sind margenstark, gehen auf der Vorlagen-Website aber völlig unter.",
    paket="Website Business", preis=2790,
    agents="SEO; Funnel; Google-Bewertungen-AI-Agent",
    agentbegr="SEO – die Seite arbeitet mit Keyword-Stuffing statt Struktur; für Oberaargau/Emmental ist lokale Sichtbarkeit der Hauptkanal. Funnel – ohne Formular gibt es keine strukturierte Offertenanfrage. Google-Bewertungen-AI-Agent – Kundenrückmeldungen werden angekündigt, aber nicht gezeigt; Reputation liegt brach.",
    upsell=1, reputation="Menüpunkt 'Kundenrückmeldungen' vorhanden, ohne sichtbar eingebundene Bewertungen.",
    aufhaenger="Ihre Seite kündigt Kundenrückmeldungen an, zeigt aber keine – und Ihre Spezialtransporte für Klavier und Tresor sind auf der Startseite gar nicht sichtbar.",
    b_web=4, b_pot=3, b_err=1, b_ag=1)

add(name="Hofmann Umzüge Worb (R. Hofmann Umzüge)", vn="Rudolf", nn="Hofmann", pos="Inhaber",
    ort="Worb", adresse="Rütiweg 20, 3076 Worb",
    tel="031 839 06 69", teldirekt="Nicht gefunden", mail="hofmann-transporte@gmx.ch", web="https://www.rudolfhofmann.ch",
    qentscheider="Firmierung 'R.Hofmann Umzüge Worb – Rudolf Hofmann' in öffentlichen Branchenverzeichnissen (local.ch, daibau.ch, die-umzuege.ch)",
    qkontakt="Firmenwebsite rudolfhofmann.ch (Impressum), search.ch",
    services="Umzüge, Räumungen, Möbeltransporte, Möbellift, Umzugsreinigung mit Abnahmegarantie, Unterhaltsreinigung, Entsorgung, Muldenservice, Einlagerung, Flohmarkt",
    ws=2,
    schwaechen="Veraltetes, bildlastiges Baukasten-Layout ohne klare Nutzerführung; kein Offerten- oder Kontaktformular (Aufforderung nur 'Rufen Sie uns an'); Social-Media-Icons sind reine Platzhalter ohne funktionierendes Ziel; Geschäfts-E-Mail läuft über eine GMX-Freemail-Adresse; keine Bewertungen, Referenzen oder Teamangaben; keine Copyright-/Aktualitätsangabe",
    chance="Sehr breites Leistungsangebot inkl. Muldenservice und Abnahmegarantie – online ist davon fast nichts strukturiert verkauft.",
    paket="Website Business", preis=2790,
    agents="Funnel; SEO; Google-Bewertungen-AI-Agent",
    agentbegr="Funnel – der einzige Weg zur Offerte ist ein Telefonanruf; ein Online-Anfrageprozess würde die Auslastung planbarer machen. SEO – Muldenservice und Umzugsreinigung sind eigene Suchintentionen, die aktuell keine eigene Seite haben. Google-Bewertungen-AI-Agent – in Portalen wird der Betrieb gelobt, die Bewertungen werden aber nicht bewirtschaftet.",
    upsell=1, reputation="In Vergleichsportalen positiv erwähnt (pünktlich, sauber, faire Preise); auf der eigenen Website sind keine Bewertungen eingebunden.",
    aufhaenger="Ihre Website bietet keine Offertenanfrage – Interessenten müssen anrufen – und Ihre Geschäftsmails laufen noch über eine GMX-Adresse.",
    b_web=4, b_pot=3, b_err=1, b_ag=1)

add(name="Bürki Umzüge und Transporte (AAB Umzüge Bürki)", vn="Nicht gefunden", nn="Bürki", pos="Inhaber (Vorname nicht gefunden)",
    ort="Spiez", adresse="Fischerweg 5, 3700 Spiez (Filiale: Jungfraustrasse 55, 3800 Interlaken)",
    tel="033 654 04 89", teldirekt="079 311 00 65 (Mobilnummer, öffentlich als Firmenkontakt publiziert)", mail="buerki.umzuege@hispeed.ch", web="https://www.buerki-umzuege.ch",
    qentscheider="Firmenname 'AAB Umzüge Bürki' bzw. 'Bürki Umzüge und Transporte' in local.ch/search.ch; Vorname des Inhabers nicht öffentlich belegt",
    qkontakt="Firmenwebsite buerki-umzuege.ch, search.ch, local.ch",
    services="Privatumzüge, Geschäftsumzüge, Transporte nah und fern, Logistik, Möbellagerung, Umzüge Schweiz und Europa",
    ws=2,
    schwaechen="Veraltetes Layout mit kleinem Logo und schwacher visueller Hierarchie; kein Offerten- oder Anfrageformular, nur ein allgemeiner Kontaktlink; Bildmaterial in schlechter Qualität; Referenzenbereich vorhanden, aber ohne Inhalt; der 'Über uns'-Link führt lediglich auf das Impressum; veraltete Social-Sharing-Buttons; keine Copyright-/Aktualitätsangabe",
    chance="Zwei Standorte (Spiez und Interlaken) im Tourismusraum Berner Oberland, deren Reichweite die Website überhaupt nicht abbildet.",
    paket="Website Business", preis=2790,
    agents="SEO; Funnel",
    agentbegr="SEO – zwei Standorte im Berner Oberland ohne eigene Standortseiten verschenken massiv lokale Sichtbarkeit für Spiez, Thun und Interlaken. Funnel – ohne Anfrageformular bleibt jede Online-Anfrage Zufall.",
    upsell=1, reputation="Der Interlakner Eintrag wird auf local.ch mit 5 Sternen geführt; auf der eigenen Website sind keine Bewertungen sichtbar.",
    aufhaenger="Sie sind in Spiez und Interlaken präsent, Ihre Website hat aber weder Standortseiten noch ein Offertenformular – und Ihr Referenzenbereich ist leer.",
    b_web=4, b_pot=2, b_err=2, b_ag=1)

add(name="Sana Umzug GmbH", vn="Saleh", nn="Mohammadpour", pos="Gesellschafter & Geschäftsführer (Einzelunterschrift)",
    ort="Köniz", adresse="Schwarzenburgstrasse 234, 3098 Köniz",
    tel="079 281 21 18", teldirekt="079 281 21 18 (Mobilnummer, als Firmenkontakt publiziert)", mail="info@sana-umzug.ch", web="https://sana-umzug.ch",
    qentscheider="Handelsregister BE / Moneyhouse (UID CHE-115.880.090), Gründung 04.08.2010",
    qkontakt="Firmenwebsite sana-umzug.ch, search.ch, local.ch",
    services="Umzüge, Räumungen, Entsorgung, Umzugsreinigung mit Abnahmegarantie",
    ws=2,
    schwaechen="Durchgehend nicht ladende SVG-Platzhalter statt echter Bilder; die Seite verweist auf ein Formular ('Bitte füllen Sie das Formular vollständig aus'), es ist aber kein Formular sichtbar; Copyright-Angabe 2026 (Template-Fehler); sehr flache Seitenstruktur ohne eigene Leistungsseiten; WhatsApp-Button nicht sauber eingebunden",
    chance="Seit 2010 im Handelsregister, Geschäftsführer klar benannt – die Website unterläuft diese Substanz komplett.",
    paket="Website Essential", preis=1790,
    agents="Funnel; SEO; Google-Bewertungen-AI-Agent",
    agentbegr="Funnel – die Seite verspricht ein Offertenformular, das gar nicht existiert; das ist der direkteste Conversion-Verlust. SEO – für 'Umzugsfirma Köniz/Bern' fehlt jede Seitenstruktur. Google-Bewertungen-AI-Agent – in Portalen wird 4.8/5 ausgewiesen, auf der Website wird das nicht genutzt.",
    upsell=1, reputation="In Vergleichsportalen mit 4.8/5 als eine der bestbewerteten Umzugsfirmen im Kanton Bern geführt; auf der eigenen Website nicht eingebunden.",
    aufhaenger="Ihre Website fordert Besucher auf, 'das Formular vollständig auszufüllen' – ein Formular ist aber gar nicht vorhanden, und die Bilder laden nicht.",
    b_web=4, b_pot=2, b_err=2, b_ag=1)

add(name="SCreinigung und Umzug GmbH", vn="Cvetko", nn="Sajn", pos="Geschäftsführer",
    ort="Aarwangen", adresse="Bannfeldstrasse 6, 4912 Aarwangen",
    tel="062 922 17 05", teldirekt="078 216 67 87 (Mobilnummer, als Firmenkontakt publiziert)", mail="info.sc.reinigung@mail.ch", web="https://screinigung.ch",
    qentscheider="Handelsregister BE / Moneyhouse (UID CHE-391.267.774), Gründung 01.09.2022; VR-Präsidentin Milanka Sajn, Geschäftsführer Cvetko Sajn",
    qkontakt="Firmenwebsite screinigung.ch, search.ch, local.ch",
    services="Umzug & Transport, Umzugsreinigung mit 100% Abnahmegarantie, Baureinigung, Spezialreinigung, Facility Management, Entsorgung",
    ws=2,
    schwaechen="Optisch stark veraltetes Layout im Stil früher 2000er-Jahre ohne visuelle Hierarchie; keine vollständige Firmenadresse auf der Seite; trotz starker Offerten-Aufforderung kein eingebettetes Formular; kein Inhaber/Verantwortlicher genannt; Fotogalerie verlinkt, aber ohne aussagekräftige Referenzbilder; defektes Navigationselement im Quelltext; Geschäftsmail über generischen mail.ch-Freemail-Dienst",
    chance="Die 100%-Abnahmegarantie ist ein starkes Verkaufsargument, das auf der veralteten Seite völlig untergeht.",
    paket="Website Essential", preis=1790,
    agents="Funnel; SEO",
    agentbegr="Funnel – die Seite ruft zur Offerte auf, bietet aber keine Eingabemöglichkeit; ein Anfrageprozess wäre der schnellste Umsatzhebel. SEO – Aarwangen/Langenthal/Oberaargau sind gut besetzbare lokale Suchräume, die aktuell nicht bedient werden.",
    upsell=1, reputation="Facebook-Seite vorhanden; Google-Bewertungen auf der Website nicht eingebunden.",
    aufhaenger="Ihre 100%-Abnahmegarantie ist ein starkes Argument – auf Ihrer Website kann man dazu aber gar keine Offerte anfordern, weil kein Formular vorhanden ist.",
    b_web=4, b_pot=2, b_err=2, b_ag=1)

add(name="Kellenberger Transporte GmbH (Kellenberger Umzüge)", vn="Cornelia", nn="Nussbaum", pos="Gesellschafterin & Geschäftsführerin",
    ort="Gümligen (Muri bei Bern)", adresse="Tannackerstrasse 25, 3073 Gümligen",
    tel="031 961 01 65", teldirekt="Nicht gefunden", mail="info@kellenberger-umzuege.ch", web="https://www.kellenberger-umzuege.ch",
    qentscheider="Handelsregister BE / Moneyhouse (UID CHE-355.603.333); Bettina Nussbaum-Jedlicka als weitere Geschäftsführerin eingetragen",
    qkontakt="Firmenwebsite kellenberger-umzuege.ch, search.ch, local.ch",
    services="Privatumzüge, Geschäftsumzüge, Spezial-/Schwertransporte, Klein- und Expresstransporte, Räumungen, Entsorgung, Einlagerung, Reinigung, Foodtruck-Transporte",
    ws=2,
    schwaechen="Veraltetes Layout ohne erkennbares Responsive-Verhalten; Zeichensatzfehler bei Umlauten in der Navigation; keine vollständige Firmenadresse auf der Website; Copyright-Angabe 2026 (Template-Fehler); keine Kundenbewertungen, Referenzen oder Zertifikate; keine Teamvorstellung trotz Familienbetrieb",
    chance="Sehr breites Transportportfolio inkl. Schwertransporten und Foodtrucks – auf der Website weder erklärt noch verkauft.",
    paket="Website Business", preis=2790,
    agents="SEO; Funnel; Google-Bewertungen-AI-Agent",
    agentbegr="SEO – Spezialtransporte und Schwertransporte sind hochwertige Suchbegriffe, für die keine eigene Seite existiert. Funnel – der Offertenlink führt nicht in eine strukturierte Anfragestrecke. Google-Bewertungen-AI-Agent – etablierter Betrieb mit Verzeichniseinträgen, aber ohne aktives Bewertungsmanagement.",
    upsell=1, reputation="Verzeichniseinträge auf local.ch/search.ch vorhanden; keine Bewertungen auf der eigenen Website.",
    aufhaenger="In Ihrer Navigation werden die Umlaute falsch dargestellt und im Footer steht 2026 – dabei sind Ihre Schwer- und Spezialtransporte online gar nicht erklärt.",
    b_web=4, b_pot=3, b_err=1, b_ag=1)

add(name="DANI-Transport (Inh. Danijela Janjic)", vn="Danijela", nn="Janjic", pos="Inhaberin",
    ort="Bern", adresse="Balthasarstrasse 17, 3027 Bern",
    tel="031 991 46 48", teldirekt="076 567 95 59 (Mobilnummer, auf der Firmenwebsite publiziert)", mail="info@dani-transport.ch", web="https://dani-transport.ch",
    qentscheider="Firmenwebsite dani-transport.ch (Firmierung als Einzelunternehmen Janjic Danijela)",
    qkontakt="Firmenwebsite dani-transport.ch, search.ch, local.ch",
    services="Privat- und Geschäftsumzüge, Ein-/Auspackservice, Einzelmöbeltransporte, interne Umzüge, Möbelmontage, Hauswartung, Winterdienst, Treppenhaus- und Wohnungsreinigung, Gartenpflege, Entsorgung",
    ws=3,
    schwaechen="Optisch veraltete Aufmachung mit Stockfoto-Slidern ohne eigenes Bildmaterial; ein Bereich 'Referenzen' wird erwähnt, aber nicht dargestellt; keine Kundenbewertungen sichtbar; die Preistabelle bricht unvollständig ab; keine Copyright-/Aktualitätsangabe",
    chance="Sehr breites Dienstleistungsspektrum (Umzug, Hauswartung, Reinigung, Garten) – online werden die Bereiche nicht sauber getrennt und verkauft.",
    paket="Website Business", preis=2790,
    agents="Funnel; SEO; Google-Bewertungen-AI-Agent",
    agentbegr="Funnel – die abgebrochene Preistabelle und der fehlende Anfrageprozess verhindern Conversion genau am Entscheidungspunkt. SEO – Umzug, Hauswartung und Reinigung brauchen eigene Landingpages, um in Bern gefunden zu werden. Google-Bewertungen-AI-Agent – Referenzen werden angekündigt, aber nicht gezeigt.",
    upsell=1, reputation="Referenzen werden erwähnt, sind aber auf der Website nicht abrufbar; keine Bewertungen eingebunden.",
    aufhaenger="Ihre Preistabelle bricht mitten in der Darstellung ab und der angekündigte Referenzbereich ist nicht abrufbar – genau dort steigen Interessenten aus.",
    b_web=3, b_pot=3, b_err=2, b_ag=1)

add(name="Hand4you.ch GmbH", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Biel/Bienne", adresse="Rue Johann-Renfer 1, 2504 Biel/Bienne",
    tel="032 351 47 47", teldirekt="Nicht gefunden", mail="info@hand4you.ch", web="https://www.hand4you.ch",
    qentscheider="Nicht gefunden – Website nennt keine verantwortliche Person",
    qkontakt="Firmenwebsite hand4you.ch, search.ch, local.ch",
    services="Umzüge, Seniorenumzüge, Räumungen, Renovationen, Malerarbeiten, Reinigung, Hauswartung",
    ws=3,
    schwaechen="Veraltetes Layout mit schwacher visueller Hierarchie; auf der Website ist keine Firmenadresse angegeben; kein Offerten- oder Anfrageformular, nur Telefon/E-Mail; keine Bewertungen, Zertifikate oder Referenzen; sprachliche Fehler im Text ('oberste Schritte'); schwache mobile Darstellung",
    chance="Seniorenumzüge sind ein beratungsintensives, margenstarkes Segment, das online überhaupt nicht positioniert ist.",
    paket="Website Business", preis=2790,
    agents="Funnel; SEO",
    agentbegr="Funnel – ohne Anfrageformular gibt es keine planbare Leadstrecke, gerade bei beratungsintensiven Seniorenumzügen. SEO – 'Seniorenumzug Biel' und 'Räumung Biel' sind konkrete lokale Suchintentionen ohne eigene Seite.",
    upsell=1, reputation="Nicht gefunden – keine Bewertungen auf der Website eingebunden.",
    aufhaenger="Sie bieten Seniorenumzüge an – ein sehr vertrauensintensives Thema – aber Ihre Website nennt weder eine Adresse noch eine Möglichkeit, online eine Offerte anzufordern.",
    b_web=3, b_pot=3, b_err=1, b_ag=1)

add(name="Rupp Umzüge GmbH", vn="Fritz", nn="Rupp", pos="Gesellschafter & Geschäftsführer",
    ort="Rüegsauschachen", adresse="Lützelflühstrasse 67, 3415 Rüegsauschachen",
    tel="079 560 26 52", teldirekt="079 560 26 52 (Mobilnummer, auf der Firmenwebsite publiziert)", mail="info@rupp-umzuege.ch", web="https://www.rupp-umzuege.ch",
    qentscheider="Handelsregister BE / Moneyhouse (UID CHE-391.605.144), Gründung 2019; Maike Rupp als weitere Geschäftsführerin eingetragen; Website nennt Fritz Rupp für persönliche Besichtigungen",
    qkontakt="Firmenwebsite rupp-umzuege.ch, search.ch, local.ch",
    services="Privat- und Geschäftsumzüge, Klavier-/Flügeltransporte, Tresorumzüge, Möbeltransporte schweizweit, Räumungen, Entsorgung, Möbeleinlagerung",
    ws=3,
    schwaechen="Technisch einfache, optisch veraltete Umsetzung (Stand ca. Mitte 2010er) ohne erkennbare Mobiloptimierung; kein Kontakt- oder Offertenformular; das Video ist nur als roher Link statt als eingebetteter Player hinterlegt; keine Copyright-/Aktualitätsangabe; keine Kundenbewertungen eingebunden",
    chance="Der Inhaber macht Besichtigungen persönlich – dieses starke Vertrauensargument ist online kaum inszeniert, und Klavier-/Tresortransporte haben keine eigene Seite.",
    paket="Website Business", preis=2790,
    agents="SEO; Funnel; Google-Bewertungen-AI-Agent",
    agentbegr="SEO – Klavier- und Tresortransporte sind margenstarke Nischenbegriffe ohne eigene Landingpage. Funnel – ohne Formular ist die Besichtigungsanfrage nicht digitalisiert. Google-Bewertungen-AI-Agent – seit 2014 aktiv, Bewertungen werden nicht sichtbar gemacht.",
    upsell=1, reputation="Pressemitteilungen auf der Website eingebunden; keine Kundenbewertungen sichtbar.",
    aufhaenger="Sie kommen für die Besichtigung persönlich vorbei – online kann man diesen Termin aber nirgends anfragen, es gibt kein Formular.",
    b_web=3, b_pot=3, b_err=2, b_ag=1)

add(name="uurs umzug und reinigung schweiz GmbH", vn="Milenko", nn="Mitrovic", pos="Geschäftsführer",
    ort="Langenthal", adresse="Gaswerkstrasse 33, 4900 Langenthal",
    tel="062 923 54 54", teldirekt="Nicht gefunden", mail="info@uurs.ch", web="https://www.uurs.ch",
    qentscheider="Handelsregister BE / Northdata, Moneyhouse (UID CHE-288.405.147), Eintrag 19.11.2024",
    qkontakt="Firmenwebsite uurs.ch, search.ch, local.ch",
    services="Umzüge, Umzugsreinigung, Unterhalts- und Gewerbereinigung, Räumungen, Liegenschaftsunterhalt, Malerarbeiten",
    ws=3,
    schwaechen="Veraltetes Layout mit flacher visueller Hierarchie und altbackenem Farb-/Schriftbild; keine Copyright-/Aktualitätsangabe; keine Team- oder Inhaberdarstellung; das grosse Einzugsgebiet (BE, SO, BS, LU, AG, JU) wird auf der Seite nicht prominent dargestellt; Cookie-Hinweis nicht sauber umgesetzt",
    chance="Bedient sechs Kantone und hat 2024er-Kundenstimmen – die Website transportiert diese Reichweite und Aktualität nicht.",
    paket="Website Business", preis=2790,
    agents="SEO; Funnel",
    agentbegr="SEO – ein Einzugsgebiet über sechs Kantone ohne Regionenseiten verschenkt sehr viel organischen Traffic. Funnel – die Angebotsanfrage ist nur ein Navigationslink, kein durchdachter Anfrageprozess.",
    upsell=1, reputation="Kundenstimmen aus 2024 auf der Website vorhanden; Transportlizenz-Logo eingebunden.",
    aufhaenger="Sie arbeiten in sechs Kantonen – auf Ihrer Website ist das aber nirgends abgebildet, und optisch wirkt der Auftritt deutlich älter als Ihre Kundenstimmen von 2024.",
    b_web=3, b_pot=3, b_err=1, b_ag=1)

add(name="MoveEx GmbH", vn="Elif", nn="Korkmaz", pos="Geschäftsführung (auf Firmenwebsite als Verantwortliche genannt)",
    ort="Bern", adresse="Jupiterstrasse 47, 3015 Bern",
    tel="031 525 75 88", teldirekt="076 526 53 31 (Mobilnummer, auf der Firmenwebsite publiziert)", mail="info@moveex.ch", web="https://www.moveex.ch",
    qentscheider="Firmenwebsite moveex.ch (Unternehmensversprechen namentlich gezeichnet)",
    qkontakt="Firmenwebsite moveex.ch, search.ch, local.ch",
    services="Umzüge, Reinigungen, Malerarbeiten",
    ws=3,
    schwaechen="Veraltetes Grundlayout mit minimaler visueller Hierarchie und altmodischer Navigation; Zeichensatzfehler in der Navigation ('ber uns' statt 'Über uns'); sehr dünne Inhalte auf den Leistungsseiten; keine Copyright-/Aktualitätsangabe; keine Bewertungen, Referenzen oder Teamdarstellung",
    chance="Drei klar abgrenzbare Geschäftsfelder (Umzug, Reinigung, Malerarbeiten), die online als eine unstrukturierte Masse erscheinen.",
    paket="Website Essential", preis=1790,
    agents="SEO; Funnel",
    agentbegr="SEO – die dünnen Leistungsseiten und Zeichensatzfehler verhindern Rankings für 'Umzugsfirma Bern'. Funnel – die 'Online Offerte' ist nur ein Hinweis, kein strukturierter Anfrageprozess.",
    upsell=1, reputation="Nicht gefunden – keine Bewertungen auf der Website eingebunden.",
    aufhaenger="In Ihrer Navigation steht durch einen Zeichensatzfehler 'ber uns' statt 'Über uns' – und Ihre drei Geschäftsfelder sind online kaum voneinander abgegrenzt.",
    b_web=3, b_pot=2, b_err=2, b_ag=1)

add(name="Transports et Matériaux Schluep SA", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="St-Imier", adresse="Marne de la Coudre, 2610 St-Imier",
    tel="079 290 22 39", teldirekt="079 290 22 39 (Mobilnummer, als Firmenkontakt publiziert)", mail="Nicht gefunden", web="https://transports-schluep.digitalone.site",
    qentscheider="Nicht gefunden – auf der Website wird keine verantwortliche Person genannt",
    qkontakt="Firmenwebsite transports-schluep.digitalone.site, search.ch, local.ch",
    services="Déménagements (Umzüge), Garde-meubles (Möbellagerung), Nettoyage (Reinigung), Transporte, Muldenservice, Schneeräumung, Baustoffhandel",
    ws=3,
    schwaechen="Reine Baukasten-Vorlage (localsearch MyWEBSITE) ohne eigenständiges Erscheinungsbild; keine E-Mail-Adresse hinterlegt; kein Offertenformular, die Terminbuchung führt auf eine externe Seite; keine Referenzen, Zertifikate oder Bewertungen; kaum eigenes Bildmaterial; keine Copyright-/Aktualitätsangabe",
    chance="Familienbetrieb mit über 10 Jahren Erfahrung im Berner Jura, der als einer der wenigen zweisprachig bedienen kann – online praktisch unsichtbar.",
    paket="Website Essential", preis=1790,
    agents="SEO; Funnel",
    agentbegr="SEO – im Berner Jura ist die lokale Konkurrenz dünn; eine eigene Website statt Baukastenseite würde schnell ranken. Funnel – ohne E-Mail und ohne Offertenformular ist die Anfragestrecke faktisch nur telefonisch.",
    upsell=1, reputation="Nicht gefunden – keine Bewertungen auf der Website; Verzeichniseinträge vorhanden.",
    aufhaenger="Ihre Seite läuft auf einer Baukastenvorlage ohne E-Mail-Adresse und ohne Offertenformular – im Berner Jura könnten Sie mit einem eigenen Auftritt schnell die Nummer 1 sein.",
    b_web=3, b_pot=3, b_err=1, b_ag=1)

add(name="R. Ueltschi Transporte/Service", vn="Nicht gefunden", nn="Ueltschi", pos="Inhaber (Vorname nicht gefunden)",
    ort="Zweisimmen", adresse="Saanenstrasse 31, 3770 Zweisimmen",
    tel="076 249 53 73", teldirekt="076 249 53 73 (Mobilnummer, als Firmenkontakt publiziert)", mail="Nicht gefunden", web="https://r-ueltschi-transporte-service.digitalone.site",
    qentscheider="Firmierung 'R. Ueltschi Transporte/Service' in search.ch; Vorname nicht öffentlich belegt",
    qkontakt="search.ch, Firmenwebsite (Baukastenseite)",
    services="Umzüge, Transporte, Räumungen, Entsorgung, Recycling, Tiertransporte, Reifenwechsel",
    ws=3,
    schwaechen="Reine Baukasten-Vorlage (localsearch/digitalone) ohne eigene Domain und ohne eigenständiges Erscheinungsbild; keine E-Mail-Adresse hinterlegt; kein Offertenformular; keine Referenzen oder Bewertungen; keine getrennte Darstellung der sehr unterschiedlichen Leistungen (Umzug vs. Tiertransport vs. Reifenwechsel)",
    chance="Im Simmental/Saanenland gibt es kaum Wettbewerb – eine eigene Domain mit klarer Leistungstrennung würde die Marktstellung sofort sichtbar machen.",
    paket="One-Pager", preis=990,
    agents="SEO; Funnel",
    agentbegr="SEO – im Simmental/Saanenland ist die lokale Konkurrenz sehr dünn, eine eigene Domain würde schnell ranken. Funnel – aktuell gibt es weder E-Mail noch Formular, jede Anfrage muss telefonisch erfolgen.",
    upsell=1, reputation="Nicht gefunden – keine Bewertungen auf der Website; Verzeichniseintrag auf search.ch vorhanden.",
    aufhaenger="Sie haben noch keine eigene Domain, sondern eine Baukastenseite – im Simmental wären Sie mit einem eigenen Auftritt sofort die sichtbarste Adresse.",
    b_web=3, b_pot=2, b_err=2, b_ag=1)

add(name="HAK Transporte GmbH", vn="Burhanettin", nn="Kilic", pos="Gesellschafter & Geschäftsführer",
    ort="Bern", adresse="Lorrainestrasse 30, 3013 Bern",
    tel="031 333 81 82", teldirekt="Nicht gefunden", mail="Nicht gefunden (nur Kontaktformular)", web="https://haktransporte.ch",
    qentscheider="Handelsregister BE / Moneyhouse, business-monitor.ch (UID CHE-114.392.528); Lilian Huguenin als weitere Gesellschafterin/Geschäftsführerin eingetragen",
    qkontakt="search.ch, local.ch (Telefonnummer); Website nennt keine Kontaktdaten",
    services="Firmenumzüge, Privatumzüge, Schwer- und Spezialtransporte mit Möbellift, Einlagerung, Reinigung mit Abgabegarantie",
    ws=4,
    schwaechen="Auf der Startseite ist weder eine Telefonnummer noch eine E-Mail-Adresse hinterlegt; keine vollständige Firmenadresse des Berner Sitzes; kein Inhaber/Verantwortlicher genannt; das eingebundene Video lässt sich nicht abspielen ('Browser unterstützt die Videowiedergabe nicht'); keinerlei Kundenbewertungen, Referenzen oder Zertifikate trotz über 20 Jahren Marktpräsenz",
    chance="Positioniert sich klar auf Firmenumzüge – ein B2B-Segment, das mit Referenzen und einer sauberen Kontaktstrecke deutlich besser verkauft würde.",
    paket="Website Business", preis=2790,
    agents="Funnel; Autonomous-Website-Lead-Scraper; SEO",
    agentbegr="Funnel – ohne Telefonnummer und E-Mail auf der Seite ist der Offertenweg unnötig lang. Autonomous-Website-Lead-Scraper – das Unternehmen positioniert sich explizit auf Firmen- und Büroumzüge und kann aktiv B2B-Neukunden suchen. SEO – 'Firmenumzug Bern' und 'Büroumzug' sind wertvolle Suchbegriffe ohne eigene Landingpage.",
    upsell=1, reputation="Keine Bewertungen auf der Website; Google-/Verzeichniseinträge vorhanden.",
    aufhaenger="Auf Ihrer Startseite steht keine Telefonnummer und keine E-Mail-Adresse, und Ihr Video lässt sich nicht abspielen – bei Firmenumzügen ist das ein teurer Reibungspunkt.",
    b_web=3, b_pot=3, b_err=1, b_ag=1)

add(name="Box Umzug GmbH", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Thun", adresse="Hofstettenstrasse 71, 3600 Thun",
    tel="033 221 12 64", teldirekt="079 660 54 70 (Mobilnummer, auf der Firmenwebsite publiziert)", mail="info@boxumzug.ch", web="https://www.boxumzug.ch",
    qentscheider="Nicht gefunden – Website nennt keine Person; Handelsregister weist nur die Umfirmierung von Shureh GmbH zu Box Umzug GmbH (21.08.2025) aus",
    qkontakt="Firmenwebsite boxumzug.ch, search.ch, local.ch",
    services="Privat- und Geschäftsumzüge, Umzugsreinigung mit Abnahmegarantie, Entsorgung, Möbeleinlagerung, internationale Umzüge",
    ws=4,
    schwaechen="Die Vertrauenszahlen stehen noch auf den Template-Platzhaltern '0 Jahre Erfahrung' und '0 Sterne bei Google'; keine vollständige Firmenadresse auf der Website; kein Inhaber/Verantwortlicher genannt; keine Handelsregister-/UID-Angabe; das Offertenformular ist nicht auf der Startseite eingebunden",
    chance="Optisch bereits moderne Seite, die durch nicht ausgefüllte Platzhalter aktiv Vertrauen zerstört – hier ist der Hebel besonders schnell sichtbar.",
    paket="Website Business", preis=2790,
    agents="Google-Bewertungen-AI-Agent; Funnel; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – auf der Seite steht '0 Sterne bei Google'; systematisches Bewertungsmanagement würde diesen Platzhalter in ein echtes Verkaufsargument verwandeln. Funnel – die Offerte liegt eine Klickebene tiefer als nötig. SEO – Thun/Berner Oberland ist ein umkämpfter, aber gut besetzbarer lokaler Markt.",
    upsell=1, reputation="Auf der Website werden '0 Sterne bei Google' ausgewiesen (nicht befüllter Platzhalter); tatsächlicher Bewertungsstand nicht verifizierbar.",
    aufhaenger="Auf Ihrer Startseite stehen noch die Platzhalter '0 Jahre Erfahrung' und '0 Sterne bei Google' – das liest ein Interessent als Warnsignal.",
    b_web=3, b_pot=3, b_err=1, b_ag=1)

add(name="Aemmer Räumungen", vn="Nicht gefunden", nn="Aemmer", pos="Inhaber (Vorname nicht gefunden)",
    ort="Steffisburg", adresse="Bernstrasse 136, 3613 Steffisburg",
    tel="079 511 05 11", teldirekt="079 511 05 11 (Mobilnummer, als Firmenkontakt publiziert)", mail="Nicht gefunden (auf der Website verschleiert)", web="https://www.aemmer-raeumungen.ch",
    qentscheider="Firmenname 'Aemmer Räumungen' in search.ch/local.ch; keine Personenangabe auf der Website, keine Handelsregister-Personendaten gefunden",
    qkontakt="Firmenwebsite aemmer-raeumungen.ch, search.ch, local.ch",
    services="Umzüge, Räumungen, Transporte, Unterhaltsreinigung, Spezialreinigung (Endreinigung, Zwischenreinigung, Grundreinigung) mit Abnahmegarantie, Hauswartung, Eventreinigung",
    ws=4,
    schwaechen="Kein Offerten- oder Anfrageformular vorhanden, Kontakt nur über Telefon und eine verschleierte E-Mail-Adresse; Fusszeile weist 'Webdesign © 2020' aus, die Seite wirkt dadurch unpflegt; keine Handelsregister-/UID-Angabe; kein Inhaber/Verantwortlicher genannt; Angabe 'Immer geöffnet' ohne konkrete Öffnungszeiten",
    chance="Sehr breite Palette von Räumung über Umzug bis Hauswartung mit Abnahmegarantie – ohne Anfrageformular bleibt der ganze Online-Traffic ungenutzt.",
    paket="Website Business", preis=2790,
    agents="Funnel; SEO; Google-Bewertungen-AI-Agent",
    agentbegr="Funnel – die Seite hat keinerlei Offertenformular, obwohl mehrere Standorte bedient werden. SEO – Räumung, Umzug und Hauswartung sind drei getrennte Suchintentionen ohne eigene Seiten. Google-Bewertungen-AI-Agent – es sind bereits drei Kundenstimmen eingebunden, die systematisch ausgebaut werden könnten.",
    upsell=1, reputation="Drei Kundenstimmen auf der Website eingebunden; kein Google-Bewertungswidget.",
    aufhaenger="Ihre Website hat kein einziges Offertenformular und im Fuss steht noch 'Webdesign © 2020' – bei mehreren Standorten ist das viel verschenkter Traffic.",
    b_web=3, b_pot=3, b_err=1, b_ag=1)

add(name="Goldenstar Umzug GmbH", vn="Mostafa", nn="Rashid", pos="Gesellschafter & Geschäftsführer (Einzelunterschrift)",
    ort="Biel/Bienne", adresse="Calvin-Weg 11, 2504 Biel/Bienne",
    tel="078 300 81 80", teldirekt="078 300 81 80 (Mobilnummer, als Firmenkontakt publiziert)", mail="Nicht gefunden", web="https://goldenstar-umzug.ch",
    qentscheider="Handelsregister BE / Moneyhouse, Gründung 2022 bzw. Geschäftsaufnahme Februar 2023",
    qkontakt="Firmenwebsite goldenstar-umzug.ch, search.ch, local.ch",
    services="Umzüge für Private und Firmen, Umzugsreinigung, Offerten innert 24 Stunden",
    ws=4,
    schwaechen="Keine E-Mail-Adresse auf der Website hinterlegt (nur Telefon und Formular); Copyright-Angabe 2023, die Seite wirkt seither nicht gepflegt; keine Kundenbewertungen, Referenzen, Erfahrungsangaben oder Versicherungsnachweise; keine Handelsregister-/UID-Angabe; sehr geringe Inhaltstiefe",
    chance="Verspricht Offerten innert 24 Stunden – ein starkes Versprechen, das ohne Vertrauenselemente und ohne E-Mail-Kanal kaum Wirkung entfaltet.",
    paket="Website Essential", preis=1790,
    agents="Google-Bewertungen-AI-Agent; Funnel; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – als junges Unternehmen ohne sichtbare Bewertungen fehlt genau das Vertrauenselement, das den Abschluss bringt. Funnel – das 24-Stunden-Offertenversprechen sollte in einen sauberen, messbaren Prozess überführt werden. SEO – Biel/Bienne verlangt eine zweisprachige lokale Struktur, die aktuell fehlt.",
    upsell=1, reputation="Keine Bewertungen auf der Website; Verzeichniseinträge auf local.ch vorhanden.",
    aufhaenger="Sie versprechen eine Offerte innert 24 Stunden, zeigen aber keine einzige Kundenbewertung – und eine E-Mail-Adresse fehlt auf der Seite ganz.",
    b_web=3, b_pot=2, b_err=2, b_ag=1)

add(name="mamo services GmbH", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Biel/Bienne", adresse="Rue de l'Argent 9, 2502 Biel/Bienne",
    tel="076 468 08 00", teldirekt="076 468 08 00 (Mobilnummer, als Firmenkontakt publiziert)", mail="info@mamo-services.ch", web="https://www.mamo-services.ch",
    qentscheider="Nicht gefunden – Website nennt keine verantwortliche Person",
    qkontakt="Firmenwebsite mamo-services.ch, search.ch, local.ch",
    services="Umzüge/Déménagements, Reinigung, Transporte, Einlagerung, Gerätevermietung, Fahrzeugvermietung",
    ws=4,
    schwaechen="Keine Firmenadresse auf der Website; kein Offerten- oder Anfrageformular und kein prominenter Handlungsaufruf; keine Kundenbewertungen, Zertifikate, Versicherungsangaben oder Teamdarstellung; Copyright-Angabe 2026 (Template-Fehler); der 'Über uns'-Bereich ist inhaltlich leer",
    chance="Zweisprachiger Anbieter in Biel mit ungewöhnlich breitem Angebot inkl. Fahrzeugvermietung – die Website verkauft davon nichts.",
    paket="Website Business", preis=2790,
    agents="Funnel; SEO; Google-Bewertungen-AI-Agent",
    agentbegr="Funnel – die Seite hat weder Formular noch klaren Handlungsaufruf, damit entsteht keine einzige messbare Anfrage. SEO – Biel/Bienne braucht eine zweisprachige lokale Struktur (DE/FR), die nicht angelegt ist. Google-Bewertungen-AI-Agent – ohne jede Bewertung fehlt bei einem breiten Dienstleistungsangebot die Vertrauensbasis.",
    upsell=1, reputation="Nicht gefunden – keine Bewertungen auf der Website eingebunden.",
    aufhaenger="Ihre Website nennt keine Adresse und hat keinen einzigen Anfrage-Button – bei einem Angebot von Umzug bis Fahrzeugvermietung bleibt so viel Potenzial liegen.",
    b_web=3, b_pot=3, b_err=1, b_ag=1)

add(name="Eckhart Service GmbH", vn="Peter", nn="Eckhart", pos="Gesellschafter & Vorsitzender der Geschäftsführung",
    ort="Worblaufen (HR-Sitz Bolligen)", adresse="Altikofenstrasse 54, 3048 Worblaufen",
    tel="031 368 16 16", teldirekt="Nicht gefunden", mail="Nicht gefunden auf der Startseite", web="https://eckhart-service.ch",
    qentscheider="Handelsregister BE / Moneyhouse; Urs Norbert Eckhart als weiterer Gesellschafter & Geschäftsführer eingetragen; Gründung 2000 durch zwei Brüder",
    qkontakt="search.ch, local.ch (Telefonnummer); Startseite ohne Kontaktdaten",
    services="Umzüge, Seniorenumzüge, Einpackhilfe, Transporte, Einlagerung, Räumungen, Entsorgung, Reinigungsarbeiten",
    ws=4,
    schwaechen="Auf der Startseite fehlen Telefonnummer, E-Mail und Adresse vollständig; kein Offerten- oder Anfrageformular; kein Preisrahmen oder Kostenhinweis; unklarer Navigationspunkt 'Mehr'; keine Kundenbewertungen oder Referenzen trotz über 20 Jahren Marktpräsenz und Zusammenarbeit mit sozialen Institutionen",
    chance="Über 20 Jahre am Markt, arbeitet mit sozialen Institutionen und ist auf Seniorenumzüge spezialisiert – die Startseite gibt Interessenten aber keinen einzigen Kontaktweg.",
    paket="Website Business", preis=2790,
    agents="Funnel; SEO; Google-Bewertungen-AI-Agent",
    agentbegr="Funnel – ohne Kontaktdaten und ohne Formular auf der Startseite bricht die Conversion sofort ab. SEO – Seniorenumzüge und Räumungen sind eigene Suchintentionen ohne eigene Seite. Google-Bewertungen-AI-Agent – langjährige Zusammenarbeit mit Institutionen liefert ideale Bewertungsgrundlage, die ungenutzt bleibt.",
    upsell=1, reputation="Keine Bewertungen auf der Website; Zusammenarbeit mit sozialen Institutionen wird nur textlich erwähnt.",
    aufhaenger="Auf Ihrer Startseite steht weder Telefonnummer noch E-Mail noch Adresse – bei Seniorenumzügen, wo Vertrauen alles ist, ist das eine echte Hürde.",
    b_web=3, b_pot=3, b_err=1, b_ag=1)

add(name="AH Quality Services (AH Quality Home, Inh. Hasani)", vn="Nicht gefunden", nn="Hasani", pos="Inhaber (Vorname nicht gefunden)",
    ort="Belp", adresse="Steinbachstrasse 61, 3123 Belp",
    tel="079 834 12 45", teldirekt="079 834 12 45 (Mobilnummer, als Firmenkontakt publiziert)", mail="Nicht gefunden (auf der Website verschleiert)", web="https://quality-home.ch",
    qentscheider="Firmierung 'AH Quality Home Hasani' in search.ch; Vorname nicht öffentlich belegt",
    qkontakt="Firmenwebsite quality-home.ch, search.ch, local.ch",
    services="Umzüge, Umzugsreinigung, Reinigung, Liegenschaftsbetreuung, Transporte, Gartenpflege, Entsorgung, Räumungen",
    ws=4,
    schwaechen="Keine vollständige Firmenadresse auf der Website; E-Mail-Adresse verschleiert und nicht lesbar; kein dediziertes Offerten-/Kostenvoranschlagsformular, nur ein einfacher Kontakt-Button; Copyright-Angabe 2026 (Template-Fehler); keine Preisangaben, keine Teamfotos, keine Qualifikationsnachweise",
    chance="Acht Dienstleistungsbereiche unter einem Dach – online fehlt jede Priorisierung und jeder klare Weg zur Offerte.",
    paket="Website Business", preis=2790,
    agents="Funnel; SEO; Insta-Agent",
    agentbegr="Funnel – ohne Offertenformular und mit verschleierter E-Mail ist die Anfragestrecke unnötig blockiert. SEO – acht Leistungen ohne eigene Seiten bedeuten null Rankings für die einzelnen Suchbegriffe. Insta-Agent – Instagram und Facebook sind bereits verlinkt und könnten regelmässig bespielt werden.",
    upsell=1, reputation="Facebook-, Instagram- und WhatsApp-Verlinkung vorhanden; keine Bewertungen auf der Website eingebunden.",
    aufhaenger="Ihre E-Mail-Adresse ist auf der Website nicht lesbar hinterlegt und im Footer steht 2026 – Interessenten haben so kaum einen bequemen Weg zur Offerte.",
    b_web=3, b_pot=3, b_err=2, b_ag=1)

add(name="Bütikofer Umzüge und Transporte", vn="Andreas", nn="Bütikofer", pos="Inhaber (Einzelunterschrift)",
    ort="Oberburg", adresse="Brunnmattstrasse 7, 3414 Oberburg",
    tel="078 201 30 70", teldirekt="078 201 30 70 (Mobilnummer, als Firmenkontakt publiziert)", mail="andreasbuetikofer1@gmx.ch", web="https://www.xn--btikofer-umzug-gsb.ch (bütikofer-umzug.ch)",
    qentscheider="Handelsregister BE / Moneyhouse (UID CHE-458.076.264), Andreas Bütikofer als Inhaber mit Einzelunterschrift",
    qkontakt="Firmenwebsite bütikofer-umzug.ch, search.ch, local.ch",
    services="Umzüge, Hausräumungen, Spezialtransporte, Entsorgung und Recycling",
    ws=4,
    schwaechen="Geschäftskorrespondenz läuft über eine private GMX-Freemail-Adresse statt über eine Domain-E-Mail; kein Offerten- oder Kostenvoranschlagsformular auf der Startseite; keine Kundenbewertungen oder Referenzen; keine Copyright-/Aktualitätsangabe; der Inhaber wird auf der Seite nicht namentlich vorgestellt, obwohl er der Betrieb ist",
    chance="Junger Einzelbetrieb (2025) mit Umlaut-Domain – ein professioneller Auftritt inklusive Domain-E-Mail würde die Preisdurchsetzung sofort verbessern.",
    paket="One-Pager", preis=990,
    agents="SEO; Funnel",
    agentbegr="SEO – als Neugründung 2025 ist lokale Auffindbarkeit in Oberburg/Burgdorf/Emmental der entscheidende Wachstumshebel. Funnel – ohne Offertenformular kommt jede Anfrage nur telefonisch zustande.",
    upsell=1, reputation="Qualitätssiegel auf der Website eingebunden; keine Kundenbewertungen sichtbar.",
    aufhaenger="Ihre Geschäftsmails laufen noch über eine GMX-Adresse und die Website hat kein Offertenformular – für einen Betrieb, der 2025 gestartet ist, ist das schnell behoben.",
    b_web=3, b_pot=2, b_err=2, b_ag=1)

add(name="ABC Umzüge GmbH", vn="Franz", nn="Kammermann", pos="Gesellschafter & Vorsitzender der Geschäftsführung",
    ort="Allmendingen bei Bern / Gümligen", adresse="Feldmattweg 27, 3112 Allmendingen b. Bern (Postfach 135, 3073 Gümligen)",
    tel="031 951 05 27", teldirekt="079 410 37 15 (Mobilnummer, öffentlich als Firmenkontakt publiziert)", mail="info@abc-umzuege.ch", web="http://www.abc-umzuege.ch",
    qentscheider="Handelsregister BE / Moneyhouse (UID CHE-113.386.962), Eintrag 19.01.2007; Sophie Gujer als weitere Gesellschafterin & Geschäftsführerin eingetragen",
    qkontakt="Firmenwebsite abc-umzuege.ch, search.ch, local.ch",
    services="Privat- und Geschäftsumzüge, Transporte, Möbelmontage/-demontage, Packmaterial und Packpersonal, Kurz- und Langzeitlagerung, Entsorgung, Räumungen, Umzugs- und Baureinigung",
    ws=4,
    schwaechen="Kein Offertenformular auf der Startseite, nur ein allgemeiner Kontakt-Button; keine Kundenbewertungen, Referenzen, Auszeichnungen oder Angaben zur Firmengeschichte trotz Handelsregistereintrag seit 2007; keine Copyright-/Aktualitätsangabe; keine Inhaber-/Teamdarstellung; sehr dünne Vertrauensebene insgesamt",
    chance="Seit 2007 im Handelsregister mit einem sehr vollständigen Umzugsportfolio – online fehlt jeder Beleg für diese Erfahrung.",
    paket="Website Business", preis=2790,
    agents="Google-Bewertungen-AI-Agent; Funnel; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – fast 20 Jahre Kundenkontakt ohne eine einzige sichtbare Bewertung ist der grösste ungenutzte Vertrauenshebel. Funnel – der Weg zur Offerte ist unnötig lang. SEO – Lagerung und Baureinigung sind eigene Suchintentionen ohne eigene Seite.",
    upsell=1, reputation="Facebook-Verlinkung vorhanden; keine Bewertungen auf der Website eingebunden.",
    aufhaenger="Sie sind seit 2007 im Handelsregister, aber auf Ihrer Website findet sich keine einzige Kundenbewertung und kein Hinweis auf diese Erfahrung.",
    b_web=3, b_pot=3, b_err=2, b_ag=1)

add(name="Home-Services GmbH (umzugreinigung-bern.ch)", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Bern", adresse="Nicht gefunden – auf der Website ist keine Firmenadresse angegeben", 
    tel="079 660 97 98", teldirekt="079 660 97 98 (Mobilnummer, als Firmenkontakt publiziert)", mail="Nicht gefunden", web="https://umzugreinigung-bern.ch",
    qentscheider="Nicht gefunden – Website nennt lediglich 'Home-Services GmbH' ohne Personenangabe",
    qkontakt="Firmenwebsite umzugreinigung-bern.ch",
    services="Umzüge, Endreinigung mit Abnahmegarantie, Büroreinigung, Fensterreinigung, Hauswartung, Entsorgung, Räumungen, Vermittlung von Haushaltspersonal",
    ws=4,
    schwaechen="Keine Firmenadresse und keine E-Mail-Adresse auf der Website; kein Impressum und keine Datenschutzangaben auffindbar; keine Handelsregister-/UID-Angabe; keine Kundenbewertungen oder Referenzen; Datumsangaben im Blog sind in die Zukunft datiert und wirken wie Testinhalte",
    chance="Moderner Auftritt mit Offertenrechner, dem aber jede rechtliche und vertrauensbildende Grundlage fehlt – ein sauberer Relaunch macht die vorhandene Conversion-Idee erst nutzbar.",
    paket="Website Business", preis=2790,
    agents="Funnel; Google-Bewertungen-AI-Agent; SEO",
    agentbegr="Funnel – der bereits vorhandene Offertenrechner ist der richtige Ansatz, aber ohne Vertrauensebene und ohne Impressum bricht die Conversion ab. Google-Bewertungen-AI-Agent – keine einzige Bewertung sichtbar. SEO – die Domain zielt sehr eng auf Umzugsreinigung, das breitere Leistungsangebot bleibt unsichtbar.",
    upsell=1, reputation="Nicht gefunden – keine Bewertungen auf der Website eingebunden.",
    aufhaenger="Ihre Website hat einen Offertenrechner, aber weder Adresse noch Impressum noch E-Mail – das bremst genau die Anfragen aus, die der Rechner erzeugt.",
    b_web=3, b_pot=3, b_err=1, b_ag=1)

add(name="AAR-Umzüge", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Grafenried", adresse="Sinfonieweg 3, 3308 Grafenried",
    tel="031 302 20 20", teldirekt="031 767 81 11 (zweite publizierte Nummer, Region)", mail="kontakt@aar-umzuege.ch", web="https://aar-umzuege.ch",
    qentscheider="Nicht gefunden – Website nennt keine verantwortliche Person",
    qkontakt="Firmenwebsite aar-umzuege.ch, local.ch",
    services="Privat- und Geschäftsumzüge, Möbeleinlagerung, Räumungen, Entsorgung, Packmaterial und Packservice, Reinigung mit Garantie, Aemme Brocki (Secondhand)",
    ws=4,
    schwaechen="Copyright-Angabe 2017 – die Seite wirkt seit Jahren nicht gepflegt; kein Offerten- oder Anfrageformular, nur Kontaktangaben; keine Kundenbewertungen oder Referenzen; kein Inhaber/Verantwortlicher genannt; trotz beworbener schweizweiter Abdeckung keine Regionen-/Standortstruktur",
    chance="Kombination aus Umzug, Lagerung und eigenem Brockenhaus ist ein echtes Alleinstellungsmerkmal, das online gar nicht erzählt wird.",
    paket="Website Business", preis=2790,
    agents="Funnel; SEO; Google-Bewertungen-AI-Agent",
    agentbegr="Funnel – ohne Anfrageformular gibt es keine messbare Leadstrecke. SEO – der Copyright-Stand 2017 deutet auf eine seit Jahren nicht gepflegte Seite; lokale Rankings für Grafenried/Burgdorf/Bern/Solothurn sind offen. Google-Bewertungen-AI-Agent – langjährige Tätigkeit ohne eine sichtbare Bewertung.",
    upsell=1, reputation="Keine Bewertungen auf der Website; Verzeichniseinträge vorhanden.",
    aufhaenger="Im Fuss Ihrer Website steht noch 2017 und es gibt kein Anfrageformular – Ihr eigenes Brockenhaus als Alleinstellungsmerkmal kommt online gar nicht vor.",
    b_web=3, b_pot=3, b_err=1, b_ag=1)

add(name="Power Umzug GmbH", vn="Veysel", nn="Duyar", pos="Gesellschafter & Geschäftsführer (Einzelunterschrift)",
    ort="Bern", adresse="Wankdorffeldstrasse 92, 3014 Bern",
    tel="031 511 30 03", teldirekt="Nicht gefunden", mail="info@powerumzug.ch", web="https://powerumzug.ch",
    qentscheider="Handelsregister BE / Tiger.ch, Moneyhouse (UID CHE-114.328.950), Gründung 02.06.2008",
    qkontakt="Firmenwebsite powerumzug.ch, search.ch, local.ch",
    services="Privat- und Geschäftsumzüge, Umzugshilfe, Möbeltransporte, Entsorgung, Räumungen, Reinigung mit Abgabegarantie, Malerarbeiten",
    ws=4,
    schwaechen="Die Startseite enthält keine H1-Hauptüberschrift – eine grundlegende SEO- und Struktur-Schwäche; auf der Startseite ist kein Formular eingebunden, obwohl Offerten beworben werden; Copyright-Angabe 2026 (Template-Fehler); die Seite lädt über 280 KB reinen HTML-Code auf einer Seite, was auf eine unstrukturierte One-Page-Ablage hindeutet; kein Inhaber/Verantwortlicher auf der Seite genannt",
    chance="Seit 2008 im Handelsregister mit vier Geschäftsfeldern – die Website ist technisch so gebaut, dass Google die Struktur kaum lesen kann.",
    paket="Website Business", preis=2790,
    agents="SEO; Funnel; Google-Bewertungen-AI-Agent",
    agentbegr="SEO – eine Startseite ohne H1 und mit über 280 KB Einzelseiten-Code ist strukturell kaum rankingfähig; hier ist der Hebel am grössten. Funnel – ohne eingebundenes Formular geht Traffic ungenutzt verloren. Google-Bewertungen-AI-Agent – seit 2008 am Markt, ohne sichtbares Bewertungsmanagement.",
    upsell=1, reputation="Verzeichnis- und Bewertungsportaleinträge vorhanden; auf der Website keine Bewertungen strukturiert eingebunden.",
    aufhaenger="Ihre Startseite hat gar keine Hauptüberschrift (H1) – Google kann dadurch kaum erkennen, wofür Sie in Bern stehen.",
    b_web=3, b_pot=3, b_err=1, b_ag=1)

add(name="PS Umzug AG", vn="Rashid", nn="Abdullah", pos="Mitglied der Geschäftsleitung / Verwaltungsrat",
    ort="Steffisburg", adresse="Bahnhofstrasse 85, 3613 Steffisburg",
    tel="0800 800 255", teldirekt="079 821 97 35 (Mobilnummer, auf der Firmenwebsite publiziert)", mail="info@ps-umzug.ch", web="https://ps-umzug.ch",
    qentscheider="Handelsregister BE / Moneyhouse, business-monitor.ch (UID CHE-321.940.577), Gründung 15.06.2021; Govand Abdullah-Mero als Zeichnungsberechtigter eingetragen",
    qkontakt="Firmenwebsite ps-umzug.ch, search.ch, local.ch",
    services="Privat-, Geschäfts- und internationale Umzüge, Reinigung, Entsorgung, Einlagerung, Transporte, Räumungen",
    ws=5,
    schwaechen="Der Bereich für Kundenstimmen ist angelegt, aber leer; keine Zertifikate, Verbandsmitgliedschaften oder Qualitätsnachweise; kein Inhaber/Verantwortlicher und keine Teamdarstellung; Copyright-Angabe 2023; die verlinkten Detailseiten zu den Leistungen sind inhaltlich nicht ausgebaut; sehr aufdringliche Cookie-Einwilligung",
    chance="AG mit Gratisnummer 0800 und internationalem Angebot – die leere Referenzsektion untergräbt genau diese Professionalität.",
    paket="Website Business", preis=2790,
    agents="Google-Bewertungen-AI-Agent; Funnel; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – die Referenzsektion ist angelegt, aber leer; systematisch gesammelte Bewertungen füllen sie sofort. Funnel – die Offertenstrecke ist vorhanden, aber ohne Vertrauensebene schwach. SEO – die Leistungsseiten sind inhaltlich zu dünn für Rankings in Thun/Steffisburg.",
    upsell=1, reputation="Referenz-/Kundenstimmenbereich vorhanden, jedoch ohne Inhalt; Verzeichniseinträge vorhanden.",
    aufhaenger="Auf Ihrer Website ist ein Bereich für Kundenstimmen angelegt, aber komplett leer – gerade bei internationalen Umzügen ist das der wichtigste Vertrauensbeweis.",
    b_web=2, b_pot=3, b_err=2, b_ag=1)

add(name="Umzug Unit GmbH", vn="Gurpreet", nn="Singh", pos="Geschäftsführer",
    ort="Lyss", adresse="Grenzstrasse 31, 3250 Lyss",
    tel="032 310 70 60", teldirekt="078 935 82 82 (Mobilnummer, auf der Firmenwebsite publiziert)", mail="info@umzug-unit.ch", web="https://www.umzug-unit.ch",
    qentscheider="Handelsregister BE / Moneyhouse (UID CHE-403.789.828), Eintrag 11.11.2024",
    qkontakt="Firmenwebsite umzug-unit.ch, search.ch, local.ch",
    services="Haushalt- und Firmenumzüge, Büroumzüge, nationale und internationale Transporte, Haushaltsreinigung",
    ws=5,
    schwaechen="Keine Kundenbewertungen, Referenzen oder Zertifikate; keine Inhaber-/Teamdarstellung; keine Copyright-/Aktualitätsangabe im Fussbereich; keine Angaben zu Reaktionszeiten oder Preisrahmen trotz beworbener Offerten; keine Handelsregister-/UID-Angabe",
    chance="Junges, professionell wirkendes Unternehmen mit klar benanntem Geschäftsführer – es fehlt ausschliesslich die Vertrauensebene, um Offerten in Aufträge zu wandeln.",
    paket="Website Essential", preis=1790,
    agents="Google-Bewertungen-AI-Agent; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – als Neugründung von 2024 ist der Aufbau sichtbarer Bewertungen der schnellste Vertrauenshebel. SEO – Lyss/Seeland und Biel sind gut besetzbare lokale Suchräume ohne eigene Standortseiten.",
    upsell=1, reputation="Keine Bewertungen auf der Website; Verzeichniseinträge auf local.ch/search.ch vorhanden.",
    aufhaenger="Ihre Website macht optisch einen guten Eindruck, zeigt aber keine einzige Kundenbewertung – bei einer Firma, die 2024 gestartet ist, ist genau das der Knackpunkt.",
    b_web=2, b_pot=3, b_err=2, b_ag=1)

add(name="Walter Lörtscher Umzüge + Transport GmbH", vn="Walter", nn="Lörtscher", pos="Inhaber/Namensgeber (Rolle laut Firmierung; HR-Personendaten nicht verifiziert)",
    ort="Biel/Bienne", adresse="Johann-Renfer-Strasse 7, 2504 Biel/Bienne",
    tel="032 322 16 56", teldirekt="079 414 72 72 (Mobilnummer, auf der Firmenwebsite publiziert)", mail="info@loertscher.ch", web="https://loertscher-transport.ch",
    qentscheider="Firmierung 'Walter Lörtscher Umzüge & Transporte' / 'Lörtscher Umzüge + Transport GmbH' laut Firmenwebsite und search.ch; die aktuelle HR-Geschäftsführung ist öffentlich nicht eindeutig belegt",
    qkontakt="Firmenwebsite loertscher-transport.ch, search.ch",
    services="Privatumzüge, Firmenumzüge, Spezialtransporte, Möbellift bis 12. Stock, Einlagerung, Entsorgung/Muldenservice, Reinigung, Fahrzeugvermietung",
    ws=5,
    schwaechen="Kein Offerten- oder Anfrageformular auf der gesamten Seite, Kontakt nur über eine Kontaktseite; Copyright-Angabe 2026 (Template-Fehler); kein Inhaber/Verantwortlicher genannt; Formatierungsfehler in der Navigation ('Offene Job`s' mit Backtick); keine Kundenbewertungen eingebunden",
    chance="ASTAG-Mitglied mit Möbellift bis 12. Stock und Fahrzeugvermietung – ohne Online-Offerte bleibt diese Ausstattung ein reines Telefonargument.",
    paket="Website Business", preis=2790,
    agents="Funnel; SEO; Google-Bewertungen-AI-Agent",
    agentbegr="Funnel – auf der ganzen Website gibt es keine Möglichkeit, online eine Offerte anzufordern. SEO – Biel/Bienne verlangt eine zweisprachige lokale Struktur, die fehlt. Google-Bewertungen-AI-Agent – etablierter ASTAG-Betrieb ohne sichtbares Bewertungsmanagement.",
    upsell=1, reputation="ASTAG-Mitgliedschaft ausgewiesen; keine Kundenbewertungen auf der Website eingebunden.",
    aufhaenger="Auf Ihrer Website kann man nirgends online eine Offerte anfordern – bei einem Möbellift bis in den 12. Stock ist das ein Argument, das Sie digital verschenken.",
    b_web=2, b_pot=3, b_err=2, b_ag=1)

add(name="Bernova Umzug", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Bern", adresse="Holenackerstrasse 1, 3027 Bern",
    tel="032 341 03 02", teldirekt="079 781 31 21 (Mobilnummer, auf der Firmenwebsite publiziert)", mail="info@bernovaumzug.ch", web="https://bernovaumzug.ch",
    qentscheider="Nicht gefunden – Website enthält kein Impressum mit Personendaten",
    qkontakt="Firmenwebsite bernovaumzug.ch",
    services="Privat- und Geschäftsumzüge, Klaviertransporte, Umzugsreinigung mit Abnahmegarantie, Entsorgung, Möbellift, internationale Umzüge, Packservice",
    ws=5,
    schwaechen="Mehrere nicht geladene SVG-Platzhalter statt echter Bilder; kein Impressum mit Verantwortlichem und keine Handelsregister-/UID-Angabe; keine Teamfotos und keine Kundenstimmen; das Offertenformular wird beworben, ist auf der Startseite aber nicht eingebunden",
    chance="Transparente Preistabellen und Versicherungsangaben sind bereits vorhanden – es fehlt die rechtliche und personelle Vertrauensebene, die den Abschluss bringt.",
    paket="Website Business", preis=2790,
    agents="Google-Bewertungen-AI-Agent; Funnel; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – ohne Impressum und ohne Kundenstimmen fehlt jede Vertrauensgrundlage, Bewertungen sind der schnellste Ersatz. Funnel – das beworbene Offertenformular ist auf der Startseite nicht eingebunden. SEO – Klaviertransport und internationale Umzüge sind eigene Suchintentionen ohne eigene Seite.",
    upsell=1, reputation="Keine Bewertungen oder Kundenstimmen auf der Website eingebunden.",
    aufhaenger="Auf Ihrer Website laden mehrere Bilder als leere Platzhalter und es gibt kein Impressum mit einer verantwortlichen Person – das kostet gerade bei grösseren Umzügen Vertrauen.",
    b_web=2, b_pot=3, b_err=1, b_ag=1)

add(name="WIDMER Umzüge Bern", vn="Nicht gefunden", nn="Widmer", pos="Inhaber (Vorname nicht gefunden)",
    ort="Bern", adresse="Freiburgstrasse 506, 3018 Bern",
    tel="031 550 09 73", teldirekt="Nicht gefunden", mail="info@widmer-transporte-umzuege.ch", web="http://widmer-transporte-umzuege.ch",
    qentscheider="Firmierung 'WIDMER Umzüge Bern' laut local.ch/search.ch; HR-Personendaten für den Berner Betrieb nicht eindeutig auffindbar (mehrere gleichnamige Widmer-Firmen in anderen Kantonen)",
    qkontakt="Firmenwebsite widmer-transporte-umzuege.ch, search.ch, local.ch",
    services="Wohnungs- und Hausumzüge, Firmen- und Büroumzüge, Seniorenumzüge, Klaviertransporte, Einpackhilfe, Umzugshelfer, Wohnungsräumungen, Endreinigung",
    ws=5,
    schwaechen="Die Website ist über die unverschlüsselte HTTP-Adresse erreichbar (kein durchgängig erzwungenes HTTPS); keine Handelsregister-/UID-Angabe und keine Rechtsform genannt; kein Inhaber/Verantwortlicher benannt; die eingebundenen Kundenstimmen wirken schablonenhaft und sind nicht überprüfbar; einzelne verlinkte Unterseiten enthalten Platzhalterinhalte",
    chance="Wirbt mit 5.0 aus 1'979 Bewertungen und über 30 Fachkräften – ohne Impressum und ohne saubere Verschlüsselung wirkt das eher unglaubwürdig als überzeugend.",
    paket="Website Business", preis=2790,
    agents="Funnel; SEO; Google-Bewertungen-AI-Agent",
    agentbegr="Funnel – das Angebotsformular ist vorhanden, aber der Prozess dahinter ist nicht sauber ausgebaut. SEO – 15 beworbene Berner Gemeinden ohne echte Standortseiten verschenken Sichtbarkeit. Google-Bewertungen-AI-Agent – die ausgewiesene Bewertungszahl sollte auf ein nachprüfbares, gepflegtes Google-Profil gestützt werden.",
    upsell=1, reputation="Auf der Website wird ein Bewertungsabzeichen mit 5.0/5 aus 1'979 Bewertungen angezeigt; die Quelle ist nicht nachprüfbar verlinkt.",
    aufhaenger="Ihre Website läuft noch unverschlüsselt über http und nennt weder Rechtsform noch verantwortliche Person – das steht im Widerspruch zu den 1'979 Bewertungen, mit denen Sie werben.",
    b_web=2, b_pot=3, b_err=1, b_ag=1)

add(name="Profix Reinigungen, Umzüge & Transporte AG", vn="Muhamet", nn="Pepaj", pos="Verwaltungsrat & Geschäftsführer (Einzelunterschrift)",
    ort="Gwatt (Thun)", adresse="Spiezstrasse 25, 3645 Gwatt (Thun)",
    tel="033 335 39 85", teldirekt="079 195 29 42 (Mobilnummer, auf der Firmenwebsite als 24/7-Nummer publiziert)", mail="info@profix-reinigungen.ch", web="https://www.profix-reinigungen.ch",
    qentscheider="Handelsregister BE / Northdata, business-monitor.ch (UID CHE-378.530.277), Gründung 28.04.2020; auf der Website als 'M. Pepaj, Geschäftsführer' ausgewiesen",
    qkontakt="Firmenwebsite profix-reinigungen.ch, search.ch, local.ch",
    services="Umzüge, Transporte, Einlagerung, Räumungen/Entsorgung, Wohnungs- und Gewerbereinigung, Umzugsreinigung, Fensterreinigung, Baureinigung, Umgebungsunterhalt",
    ws=5,
    schwaechen="Der Newsbereich enthält als jüngste Beiträge Corona-Meldungen von März 2020 – die Seite wirkt inhaltlich seit fünf Jahren stehengeblieben; Copyright-Angabe 2020; Tippfehler in einer Navigations-URL ('renigung-checkliste'); die Umzugsleistungen sind gegenüber der Reinigung deutlich untergewichtet, obwohl Umzug im Firmennamen steht",
    chance="Der Firmenname führt 'Umzüge und Transporte', die Website verkauft aber fast ausschliesslich Reinigung – ein klar getrennter Umzugs-Auftritt würde ein zweites Standbein sichtbar machen.",
    paket="Website Business", preis=2790,
    agents="SEO; Funnel; Google-Bewertungen-AI-Agent",
    agentbegr="SEO – 'Umzugsfirma Thun' wird trotz Firmenname praktisch nicht bedient, weil die Umzugsseiten fehlen. Funnel – der Offertenrechner ist vorhanden, aber nur auf Reinigung ausgelegt. Google-Bewertungen-AI-Agent – Google-Kundenstimmen sind bereits eingebunden und könnten systematisch ausgebaut werden.",
    upsell=1, reputation="Google-Kundenstimmen auf der Website eingebunden; Referenzenseite vorhanden.",
    aufhaenger="Ihr Firmenname führt Umzüge und Transporte, Ihre Website verkauft aber fast nur Reinigung – und der Newsbereich zeigt noch Corona-Meldungen von März 2020.",
    b_web=2, b_pot=3, b_err=2, b_ag=1)

add(name="Schubi's Zügelbox GmbH", vn="Axel Ernst", nn="Schubert", pos="Gesellschafter & Geschäftsführer (Einzelunterschrift)",
    ort="Brügg BE", adresse="Industriestrasse 37a, 2555 Brügg BE (Zweitstandort: Seestrasse 16, 3600 Thun)",
    tel="076 490 95 64", teldirekt="076 490 95 64 (Mobilnummer, als Firmenkontakt publiziert)", mail="info@zuegel.ch", web="https://zuegel.ch",
    qentscheider="Handelsregister BE / Moneyhouse (UID CHE-328.369.181); Impressum der Firmenwebsite",
    qkontakt="Firmenwebsite zuegel.ch (Impressum), search.ch, local.ch",
    services="Umzüge, Transporte, Entsorgung, Einlagerung, Packmaterial, Fahrzeug- und Gerätemiete, Reinigung, Möbelmontage, Umzugsbewilligungen, Aktenvernichtung, internationale Zollabwicklung",
    ws=5,
    schwaechen="Kein Offertenformular auf der Startseite eingebunden, obwohl auf ein Formular verwiesen wird; keine Copyright-/Aktualitätsangabe; kein Geschäftsführer auf der Website genannt; der Mitarbeiter-Login verweist auf einen Staging-Server, was unprofessionell und aus Sicherheitssicht heikel wirkt; keine Kundenbewertungen eingebunden",
    chance="Sehr ungewöhnlich breites Portfolio inkl. Umzugsbewilligungen, Aktenvernichtung und Zollabwicklung – ein klares B2B-Profil, das online nicht als solches verkauft wird.",
    paket="Website Business", preis=2790,
    agents="Funnel; Autonomous-Website-Lead-Scraper; SEO",
    agentbegr="Funnel – auf der Startseite ist trotz Verweis kein Formular eingebunden. Autonomous-Website-Lead-Scraper – Aktenvernichtung, Umzugsbewilligungen und Zollabwicklung sind klassische B2B-Leistungen, für die aktiv Firmenkunden gesucht werden können. SEO – zwei Standorte (Brügg und Thun) ohne eigene Standortseiten.",
    upsell=1, reputation="Keine Bewertungen auf der Website; Social-Media- und WhatsApp-Kanäle verlinkt.",
    aufhaenger="Ihr Mitarbeiter-Login zeigt noch auf einen Staging-Server und auf der Startseite fehlt das Offertenformular – dabei wären Aktenvernichtung und Zollabwicklung starke B2B-Argumente.",
    b_web=2, b_pot=3, b_err=2, b_ag=1)

add(name="Zügel-Farm Team GmbH", vn="Andrin", nn="Schmutz", pos="Gesellschafter & Geschäftsführer",
    ort="Gasel (Gemeinde Köniz)", adresse="Mengestorfbergstrasse 190, 3144 Gasel",
    tel="031 521 96 67", teldirekt="Nicht gefunden", mail="info@zuegelfarmteam.ch", web="https://zuegelfarmteam.ch",
    qentscheider="Handelsregister BE / Moneyhouse, business-monitor.ch (UID CHE-295.968.622), Gründung 2013; zusätzlich auf der Firmenwebsite im Kontaktbereich genannt",
    qkontakt="Firmenwebsite zuegelfarmteam.ch, search.ch, local.ch",
    services="Privatumzüge im In- und Ausland, Klaviertransporte, Transporte, Möbelmontage/-demontage, Geschäfts- und Büroumzüge, Räumungen, Entsorgung",
    ws=5,
    schwaechen="Keine vollständige Strassenadresse mit Postleitzahl auf der Website; keine Handelsregister-/UID-Angabe; keine Öffnungszeiten; keine Copyright-/Aktualitätsangabe; keine Kundenbewertungen, Referenzen oder Zertifikate; die Felder des Kontaktformulars sind nicht auf eine Offertenanfrage zugeschnitten",
    chance="Seit 2013 im Handelsregister mit namentlich sichtbarem Geschäftsführer – es fehlt ausschliesslich die Vertrauens- und Conversion-Ebene.",
    paket="Website Essential", preis=1790,
    agents="Google-Bewertungen-AI-Agent; Funnel; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – über zehn Jahre Kundenkontakt ohne eine sichtbare Bewertung ist der grösste ungenutzte Hebel. Funnel – das Kontaktformular ist nicht als Offertenstrecke aufgebaut. SEO – Köniz/Bern-Süd ist ein klar abgrenzbarer lokaler Markt ohne eigene Seitenstruktur.",
    upsell=1, reputation="Keine Bewertungen auf der Website; Verzeichniseinträge und Bewertungsportal-Einträge vorhanden.",
    aufhaenger="Sie sind seit 2013 unterwegs, aber auf der Website fehlen Adresse, Öffnungszeiten und jede Kundenbewertung – dabei stehen Sie mit Ihrem Namen dahinter.",
    b_web=2, b_pot=3, b_err=2, b_ag=1)

add(name="A Swift Umzug & Reinigung GmbH", vn="Ramazan", nn="Akman", pos="Gesellschafter & Geschäftsführer",
    ort="Gwatt (Thun)", adresse="Chanderbrügg 31, 3645 Gwatt (Thun)",
    tel="033 336 82 47", teldirekt="077 991 39 91 (Mobil-/WhatsApp-Nummer, auf der Firmenwebsite publiziert)", mail="info@aswiftumzug.ch", web="https://www.aswiftumzug.ch",
    qentscheider="Handelsregister BE / Moneyhouse, business-monitor.ch (UID CHE-456.374.733), Gründung 11.01.2024",
    qkontakt="Firmenwebsite aswiftumzug.ch, search.ch, local.ch",
    services="Umzüge, Reinigung, Entsorgung, Einlagerung, Möbelmontage",
    ws=5,
    schwaechen="Copyright-Angabe 2026 (Template-Fehler bei einem 2024 gegründeten Unternehmen); kein eingebettetes Offertenformular auf der Startseite trotz beworbener Gratisofferte; kein Geschäftsführer auf der Website genannt; sehr knappe Leistungsbeschreibungen ohne Detailseiten; keine Kundenbewertungen oder Referenzen",
    chance="Erst 2024 gegründet und optisch bereits ordentlich – mit Vertrauenselementen und einem echten Offertenprozess wäre das Wachstum deutlich planbarer.",
    paket="Website Essential", preis=1790,
    agents="Google-Bewertungen-AI-Agent; Funnel; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – bei einer Gründung von 2024 entscheiden sichtbare Bewertungen über den Zuschlag. Funnel – die Gratisofferte wird beworben, aber nicht als Formular angeboten. SEO – Thun/Gwatt/Steffisburg ist ein dichter Markt, in dem Sichtbarkeit über den Auftrag entscheidet.",
    upsell=1, reputation="Keine Bewertungen auf der Website; Einträge auf Vergleichsportalen vorhanden.",
    aufhaenger="Sie bewerben eine kostenlose Offerte, es gibt auf der Seite aber kein Formular dafür – und im Fuss steht 2026, obwohl Sie 2024 gestartet sind.",
    b_web=2, b_pot=2, b_err=2, b_ag=1)

add(name="Umzug Revassi (Umzügerevassi)", vn="Nicht gefunden", nn="Revassi", pos="Inhaber (Vorname nicht gefunden; auf der Website als 'Herr Revassi' genannt)",
    ort="Biel/Bienne", adresse="Bözingenstrasse 138, 2504 Biel/Bienne",
    tel="079 176 70 31", teldirekt="076 471 25 90 (zweite Mobilnummer, auf der Firmenwebsite publiziert)", mail="info@umzugrevassi.ch", web="https://umzugrevassi.ch",
    qentscheider="Firmenwebsite umzugrevassi.ch (Kundenstimmen nennen 'Herr Revassi'); vollständiger Name im Handelsregister nicht auffindbar",
    qkontakt="Firmenwebsite umzugrevassi.ch, search.ch, local.ch",
    services="Privatumzüge national und international, Umzugsreinigung, Entsorgung, Möbeleinlagerung, Transporte, Packservice",
    ws=5,
    schwaechen="Der vollständige Name des Inhabers und die Rechtsform werden nicht genannt; Instagram- und X-Verlinkungen sind reine Platzhalter ('#') ohne Ziel; keine Copyright-/Aktualitätsangabe; CHE- und Steuernummer werden angegeben, ohne dass die Firmierung dazu klar ist",
    chance="Zwei Standorte und eine ausgewiesene Haftpflichtversicherung – die Seite untergräbt diese Seriosität durch fehlende Firmierung und tote Social-Links.",
    paket="Website Essential", preis=1790,
    agents="SEO; Google-Bewertungen-AI-Agent",
    agentbegr="SEO – Biel/Bienne braucht eine zweisprachige lokale Struktur (DE/FR), die aktuell fehlt. Google-Bewertungen-AI-Agent – die Website zeigt bereits Kundenstimmen mit Namen; ein gepflegtes Google-Profil würde diese verifizierbar machen.",
    upsell=1, reputation="Kundenstimmen mit Namen auf der Website eingebunden; Haftpflichtversicherungsnummer ausgewiesen; kein Google-Bewertungswidget.",
    aufhaenger="Auf Ihrer Website führen die Instagram- und X-Icons ins Leere und die vollständige Firmierung fehlt – das passt nicht zu Ihren namentlichen Kundenstimmen.",
    b_web=2, b_pot=2, b_err=2, b_ag=1)

add(name="Wisho Transport GmbH (Seegruppe GmbH)", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Bern", adresse="Pestalozzistrasse 40, 3007 Bern",
    tel="031 371 17 53", teldirekt="Nicht gefunden", mail="Nicht gefunden (auf der Website verschleiert)", web="https://wishotransport.ch",
    qentscheider="Nicht gefunden – Website nennt keine verantwortliche Person, HR-Personendaten nicht eindeutig zuordenbar",
    qkontakt="Firmenwebsite wishotransport.ch, search.ch, local.ch",
    services="Privat- und Geschäftsumzüge, Reinigung mit Abgabegarantie; weitere Standorte in Basel, Mauensee und Villarepos",
    ws=6,
    schwaechen="Der Abschnitt 'Google-Bewertungen' ist zwar angelegt, zeigt aber weder Sternebewertung noch konkrete Kundenstimmen; kein Geschäftsführer/Verantwortlicher genannt; E-Mail-Adresse verschleiert; die weiteren Standorte haben keine eigenen Seiten",
    chance="Vier Standorte in vier Kantonen ohne Standortseiten – die Website nutzt die vorhandene Reichweite gar nicht.",
    paket="Website Business", preis=2790,
    agents="Google-Bewertungen-AI-Agent; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – der Bewertungsabschnitt ist angelegt, aber leer; genau dafür ist der Agent gemacht. SEO – vier Standorte ohne eigene Standortseiten verschenken erheblichen lokalen Traffic.",
    upsell=1, reputation="Abschnitt 'Google-Bewertungen' auf der Website vorhanden, jedoch ohne sichtbare Sterne oder Kundenstimmen.",
    aufhaenger="Sie haben auf Ihrer Website einen Bereich für Google-Bewertungen, aber dort wird weder eine Note noch eine Kundenstimme angezeigt.",
    b_web=2, b_pot=3, b_err=1, b_ag=1)

add(name="REIMAL AG", vn="Ivo", nn="Milos", pos="Geschäftsführer & Mitglied des Verwaltungsrats",
    ort="Gümligen", adresse="Worbstrasse 201, 3073 Gümligen",
    tel="031 991 61 66", teldirekt="Nicht gefunden", mail="info@reimal.ch", web="https://www.reimal.ch",
    qentscheider="Handelsregister BE / Moneyhouse, pappers.ch (UID CHE-105.415.828); Davide Fiorito und Peter Rickli als weitere Geschäftsleitungsmitglieder",
    qkontakt="Firmenwebsite reimal.ch, search.ch, local.ch",
    services="Umzüge, Reinigung, Facility Services, Räumungen/Transporte, Liegenschaftsbetreuung, Malerarbeiten, Fahrzeugvermietung",
    ws=6,
    schwaechen="Zahlreiche SVG-Grafiken laden nicht und erscheinen als leere Platzhalter; der E-Mail-Link ist falsch beschriftet ('info@email.ch' statt info@reimal.ch); im Fussbereich steht '© . All Rights Reserved' ohne Jahreszahl; einzelne Menüpunkte sind doppelt vorhanden",
    chance="ISO-zertifiziert, seit 1998 am Markt und mit Lehrbetrieb – technische Fehler wie ein falscher E-Mail-Link kosten hier direkt Anfragen.",
    paket="Website Premium", preis=4490,
    agents="Funnel; SEO; Meta-Agent",
    agentbegr="Funnel – ein falsch beschrifteter E-Mail-Link mitten in der Kontaktstrecke ist ein direkter Anfrageverlust. SEO – sieben Geschäftsfelder ohne konsequente Seitenstruktur. Meta-Agent – bei dieser Grösse und Zahl an Geschäftsfeldern müssten mehrere Automatisierungen koordiniert zusammenspielen.",
    upsell=1, reputation="Kundenstimmen sowie ZPK- und Allpura-Gütesiegel auf der Website eingebunden.",
    aufhaenger="Auf Ihrer Website steht als E-Mail-Link 'info@email.ch' statt info@reimal.ch und mehrere Grafiken laden nicht – bei einem ISO-zertifizierten Betrieb fällt das auf.",
    b_web=2, b_pot=3, b_err=1, b_ag=1)

add(name="Hirschen Umzug GmbH", vn="Delil", nn="Tekin", pos="Geschäftsführer (Einzelunterschrift)",
    ort="Biel/Bienne", adresse="Ohm-Weg 10, 2504 Biel/Bienne (HR-Adresse: Reitschulstrasse 5, 2502 Biel/Bienne)",
    tel="032 345 10 00", teldirekt="Nicht gefunden", mail="info@hirschenumzug.ch", web="https://hirschenumzug.ch",
    qentscheider="Handelsregister BE / Moneyhouse, business-monitor.ch (UID CHE-473.716.220), Gründung 2022; Ava Azizoska als Vorsitzende der Geschäftsführung eingetragen",
    qkontakt="Firmenwebsite hirschenumzug.ch, search.ch, local.ch",
    services="Privatumzüge, Firmenumzüge, internationale Transporte, Klaviertransporte, Möbellift, Umzugsreinigung, Entsorgung, Einlagerung",
    ws=6,
    schwaechen="Mehrere SVG-Platzhalterbilder laden nicht; im Fussbereich fehlt die Jahresangabe ('All Rights Reserved' ohne Jahr); kein Geschäftsführer auf der Website genannt; die beworbene Abnahmegarantie wird nirgends mit Bedingungen oder Versicherungsnachweis unterlegt",
    chance="5.0 aus 36 Google-Bewertungen ist ein starkes Verkaufsargument – die technischen Bildfehler und die fehlende Absicherung der Garantie bremsen es aus.",
    paket="Website Business", preis=2790,
    agents="SEO; Google-Bewertungen-AI-Agent",
    agentbegr="SEO – Biel/Bienne verlangt eine zweisprachige Struktur (DE/FR), die aktuell fehlt. Google-Bewertungen-AI-Agent – mit 5.0 aus 36 Bewertungen besteht eine sehr gute Basis, die systematisch ausgebaut und beantwortet werden sollte.",
    upsell=1, reputation="5.0 von 5 Sternen bei 36 Google-Bewertungen, auf der Website eingebunden; transparente Preistabellen vorhanden.",
    aufhaenger="Ihre 5.0 aus 36 Google-Bewertungen sind stark – gleichzeitig laden auf der Seite mehrere Bilder nicht und Ihre Abnahmegarantie ist nirgends abgesichert.",
    b_web=2, b_pot=3, b_err=1, b_ag=1)

add(name="Melian's Umzüge & Reinigungen GmbH", vn="Masar", nn="Berisha", pos="Gesellschafter & Geschäftsführer",
    ort="Thun", adresse="Scheibenstrasse 63, 3600 Thun",
    tel="076 320 20 21", teldirekt="076 320 20 21 (Mobilnummer, als Firmenkontakt publiziert)", mail="info@melians-umzuege.ch", web="https://www.melians-umzuege.ch",
    qentscheider="Handelsregister BE / Moneyhouse, business-monitor.ch (UID CHE-328.277.780), Gründung 2022",
    qkontakt="Firmenwebsite melians-umzuege.ch, search.ch, local.ch",
    services="Umzüge, Reinigung, Möbeleinlagerung, Autovermietung, Entsorgung, Klaviertransporte, Räumungen, Zwischenlagerung",
    ws=6,
    schwaechen="Widersprüchliche Adressangaben zwischen Kopf- und Fussbereich (Scheibenstrasse 63, 3600 Thun gegenüber Schorenstrasse 48, 3645); Copyright-Angabe 2026 (Template-Fehler); kein Geschäftsführer auf der Website genannt; das Offertenformular wird verlinkt, ist aber nicht sichtbar eingebunden; mehrere Verweise auf fremde Domains lassen die Markenführung unklar erscheinen",
    chance="4.9 aus 116 Bewertungen und CHF 10 Mio. Versicherungsdeckung – zwei widersprüchliche Adressen auf derselben Seite stellen genau diese Seriosität in Frage.",
    paket="Website Business", preis=2790,
    agents="Google-Bewertungen-AI-Agent; Funnel; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – mit 4.9 aus 116 Bewertungen ist eine sehr starke Basis vorhanden, die konsequent beantwortet und ausgebaut werden sollte. Funnel – das Offertenformular ist nur verlinkt, nicht eingebunden. SEO – die Verweise auf mehrere Fremddomains verwässern die eigene Domainstärke.",
    upsell=1, reputation="4.9 von 5 Sternen bei 116 Bewertungen mit datierten Kundenstimmen auf der Website; Versicherungsdeckung bis CHF 10 Mio. ausgewiesen.",
    aufhaenger="Auf Ihrer Website stehen im Kopf und im Fuss zwei verschiedene Adressen – bei 4.9 Sternen aus 116 Bewertungen ist das ein unnötiger Stolperstein.",
    b_web=2, b_pot=3, b_err=2, b_ag=1)

add(name="Rund Umzug GmbH", vn="Farzaneh", nn="Mussavi", pos="Gesellschafterin & Vorsitzende der Geschäftsführung (Einzelunterschrift)",
    ort="Thun", adresse="Adlerstrasse 4, 3604 Thun",
    tel="076 265 80 00", teldirekt="076 265 80 00 (Mobilnummer, als Firmenkontakt publiziert)", mail="info@rund-umzug.ch", web="https://rund-umzug.ch",
    qentscheider="Handelsregister BE / Moneyhouse, business-monitor.ch (UID CHE-155.457.154), Eintrag 04.02.2025; Nasar Ahmad Akbari als weiterer Geschäftsführer eingetragen",
    qkontakt="Firmenwebsite rund-umzug.ch, search.ch, local.ch",
    services="Umzüge, Umzugsreinigung, Büroumzüge, Entsorgung, Einlagerung, Möbelmontage, Klaviertransporte, Secondhand-Handel",
    ws=6,
    schwaechen="Die beworbenen Kennzahlen ('1000+ Umzüge', '10+ Jahre Erfahrung') stehen im Widerspruch zum Handelsregistereintrag vom Februar 2025 und wirken dadurch unglaubwürdig; kein Geschäftsführer auf der Website genannt; keine Versicherungs- oder Zertifikatsangaben; keine Handelsregister-/UID-Angabe",
    chance="Optisch bereits solide Seite mit klarer Offertenstrecke – die widersprüchlichen Erfahrungsangaben sind das grösste Vertrauensrisiko.",
    paket="Website Essential", preis=1790,
    agents="Google-Bewertungen-AI-Agent; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – echte, verifizierbare Bewertungen ersetzen die aktuell unbelegten Erfahrungszahlen. SEO – Thun ist ein umkämpfter lokaler Markt, in dem eine Neugründung Sichtbarkeit aktiv aufbauen muss.",
    upsell=1, reputation="Auf der Website werden '1000+ Umzüge' und eine Zufriedenheitsgarantie beworben; unabhängig verifizierbare Bewertungen sind nicht eingebunden.",
    aufhaenger="Ihre Website wirbt mit über 10 Jahren Erfahrung, im Handelsregister sind Sie seit Februar 2025 eingetragen – solche Widersprüche prüfen Kunden heute nach.",
    b_web=2, b_pot=2, b_err=2, b_ag=1)

add(name="Schmid Transport & Reinigung GmbH", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Zollikofen", adresse="Industriestrasse 35, 3052 Zollikofen",
    tel="031 333 14 64", teldirekt="Nicht gefunden", mail="info@schmid-transport-reinigung.ch", web="https://www.schmid-transport-reinigung.ch",
    qentscheider="Nicht gefunden – Website nennt keine verantwortliche Person",
    qkontakt="Firmenwebsite schmid-transport-reinigung.ch",
    services="Privatumzüge, Firmenumzüge, internationale Umzüge, Reinigung, Entsorgung, Klaviertransporte, Möbelvermietung, Einlagerung",
    ws=6,
    schwaechen="Copyright-Angabe 2023 – die Seite wirkt seit zwei Jahren nicht gepflegt; kein Geschäftsführer/Verantwortlicher genannt; die Filiale 'Zürich' ist mit einer Adresse in Baar (Kanton Zug) hinterlegt, was widersprüchlich wirkt; keine Handelsregister-/UID-Angabe",
    chance="Vier Standorte und ein 4.6-Sterne-Schnitt – der Auftritt wirkt trotzdem seit 2023 eingefroren und widersprüchlich.",
    paket="Website Business", preis=2790,
    agents="SEO; Google-Bewertungen-AI-Agent",
    agentbegr="SEO – vier Standorte mit widersprüchlichen Adressangaben schaden der lokalen Auffindbarkeit direkt. Google-Bewertungen-AI-Agent – 4.6/5 ist eine gute Basis, die aktiv gepflegt werden sollte.",
    upsell=1, reputation="4.6 von 5 Sternen auf der Website ausgewiesen; Zufriedenheitsgarantie beworben.",
    aufhaenger="Ihre Filiale 'Zürich' ist auf der Website mit einer Adresse in Baar hinterlegt und im Fuss steht noch 2023 – das irritiert bei vier Standorten.",
    b_web=2, b_pot=3, b_err=1, b_ag=1)

add(name="Kastrati Transport GmbH", vn="Fadil", nn="Kastrati", pos="Gesellschafter & Geschäftsführer (Einzelunterschrift)",
    ort="Biel/Bienne (HR-Sitz Orpund)", adresse="Johann-Renfer-Strasse 62, 2504 Biel/Bienne (HR-Sitz: Lindenstrasse 12, 2552 Orpund)",
    tel="079 813 23 47", teldirekt="079 813 23 47 (Mobilnummer, als Firmenkontakt publiziert)", mail="kastratitransport@hotmail.com", web="https://www.kastratitransport.ch",
    qentscheider="Handelsregister BE / Moneyhouse, handelsregister.help.ch (UID CHE-463.167.487)",
    qkontakt="Firmenwebsite kastratitransport.ch, search.ch, local.ch",
    services="Umzüge, Transporte und Logistik, Entsorgung und Entrümpelung, Autotransporte",
    ws=6,
    schwaechen="Geschäftskorrespondenz läuft über eine Hotmail-Freemail-Adresse statt über eine Domain-E-Mail; keine Copyright-/Aktualitätsangabe; kein Geschäftsführer und keine Handelsregister-/UID-Angabe auf der Website; die genannte Zahl '500+ Umzüge' ist nicht mit einer Quelle unterlegt",
    chance="Optisch guter Auftritt mit Kundenstimmen – die Hotmail-Adresse zerstört den professionellen Eindruck genau im Moment der Kontaktaufnahme.",
    paket="Website Essential", preis=1790,
    agents="Google-Bewertungen-AI-Agent; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – die angegebenen 500+ Umzüge sollten durch echte, öffentlich sichtbare Bewertungen belegt werden. SEO – Biel/Bienne braucht eine zweisprachige Struktur (DE/FR), die aktuell fehlt.",
    upsell=1, reputation="Kundenstimmen mit Namen auf der Website eingebunden; kein Google-Bewertungswidget.",
    aufhaenger="Ihre Website macht einen guten Eindruck, aber Ihre Geschäftsmails laufen noch über eine Hotmail-Adresse – das fällt Firmenkunden sofort auf.",
    b_web=2, b_pot=2, b_err=2, b_ag=1)

add(name="SwissCleanMove", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Biel/Bienne", adresse="Orpundstrasse 31, 2504 Biel/Bienne",
    tel="078 215 80 30", teldirekt="076 488 36 89 (zweite Mobilnummer, auf der Firmenwebsite publiziert)", mail="info@swisscleanmove.ch", web="https://www.swisscleanmove.ch",
    qentscheider="Nicht gefunden – Website nennt keine verantwortliche Person, keine Rechtsform angegeben",
    qkontakt="Firmenwebsite swisscleanmove.ch, local.ch",
    services="Umzüge und Transporte, Umzugsreinigung mit 100% Abnahmegarantie, Fensterreinigung, Baureinigung, Unterhaltsreinigung, Entsorgung, Räumungen, Haushaltshilfe",
    ws=6,
    schwaechen="Copyright-Angabe 2026 (Template-Fehler); keine Rechtsform und keine Handelsregister-/UID-Angabe; kein Inhaber/Verantwortlicher genannt; der Google-Schnitt beruht auf lediglich 10 Bewertungen, was für die beworbene 'Schweizer Qualität' eine dünne Basis ist",
    chance="Bereits saubere Conversion-Struktur mit klaren Offerten-Buttons – es fehlt die rechtliche und personelle Vertrauensebene sowie eine belastbare Bewertungsbasis.",
    paket="Website Business", preis=2790,
    agents="Google-Bewertungen-AI-Agent; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – 10 Bewertungen sind für einen Anbieter mit diesem Anspruch zu wenig; systematischer Aufbau ist der direkteste Hebel. SEO – Biel/Bienne, Bern und Zürich werden beworben, aber ohne konsequente Standortstruktur.",
    upsell=1, reputation="4.4 von 5 Sternen bei 10 Google-Bewertungen, auf der Website eingebunden; Haftpflichtversicherung ausgewiesen.",
    aufhaenger="Sie werben mit zertifiziertem Fachpersonal, stützen sich online aber auf nur 10 Google-Bewertungen – und eine Rechtsform ist auf der Seite gar nicht genannt.",
    b_web=2, b_pot=3, b_err=1, b_ag=1)

add(name="Umzug Profis Bern", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Bern", adresse="Mühledorfstrasse 1, 3018 Bern",
    tel="078 720 80 05", teldirekt="078 720 80 05 (Mobilnummer, als Firmenkontakt publiziert)", mail="info@umzugprofis.ch", web="https://umzugprofis.ch",
    qentscheider="Nicht gefunden – Website nennt keine verantwortliche Person und keine Rechtsform",
    qkontakt="Firmenwebsite umzugprofis.ch, search.ch, local.ch",
    services="Privat- und Geschäftsumzüge, Umzugsreinigung mit Abnahmegarantie, Möbelentsorgung, Transporte, Möbellift, Büroumzüge, internationale Umzüge, Fenster- und Fassadenreinigung, Lagerraumvermietung",
    ws=6,
    schwaechen="Keine vollständige Firmenadresse und keine Rechtsform auf der Startseite; kein Inhaber/Verantwortlicher genannt; keine Handelsregister-/UID-Angabe; mehrere Inhaltsabschnitte wiederholen sich; die Standortseiten sind nur über den Fussbereich erreichbar",
    chance="Sehr gut ausgebaute Offertenstrecke und Versicherungsnachweise – es fehlen ausgerechnet die rechtlichen Basisangaben, die B2B-Kunden zuerst prüfen.",
    paket="Website Premium", preis=4490,
    agents="SEO; Autonomous-Website-Lead-Scraper; Meta-Agent",
    agentbegr="SEO – sieben beworbene Kantone ohne saubere Standortarchitektur verschenken sehr viel lokalen Traffic. Autonomous-Website-Lead-Scraper – Büroumzüge und Gewerbereinigung sind ausgewiesene Leistungen, für die aktiv Firmenkunden gesucht werden können. Meta-Agent – bei dieser Standort- und Leistungsbreite müssen mehrere Automatisierungen koordiniert werden.",
    upsell=1, reputation="Mehrere Kundenstimmen mit 5-Sterne-Bewertungen sowie Partnerlogos (Zurich, AXA, SUVA) auf der Website eingebunden.",
    aufhaenger="Ihre Offertenstrecke ist stark, aber auf der Website steht weder eine vollständige Adresse noch eine Rechtsform – genau das prüfen Firmenkunden vor einem Büroumzug zuerst.",
    b_web=2, b_pot=3, b_err=1, b_ag=1)

add(name="Goldpferd Umzug", vn="Nicht gefunden", nn="Nicht gefunden", pos="Nicht gefunden",
    ort="Belp", adresse="Muristrasse 3, 3123 Belp",
    tel="031 819 10 88", teldirekt="Nicht gefunden", mail="Nicht gefunden (auf der Website verschleiert)", web="https://goldpferdumzug.ch",
    qentscheider="Nicht gefunden – Website nennt keine verantwortliche Person",
    qkontakt="Firmenwebsite goldpferdumzug.ch, search.ch, local.ch",
    services="Privat- und Geschäftsumzüge, Umzugsreinigung, Einlagerung, Entsorgung, Möbelmontage, Klaviertransporte, Kleintransporte, Packservice, internationale Umzüge mit Zollabwicklung",
    ws=6,
    schwaechen="Copyright-Angabe 2026 mit Fremdname ('© 2026 Somion') statt eigener Firmierung; kein Inhaber/Verantwortlicher genannt; E-Mail-Adresse verschleiert; mehrere Inhaltsabschnitte wiederholen sich; der Link 'Das ganze Team kennenlernen' führt zu keiner echten Teamdarstellung",
    chance="ASTAG-Mitglied mit 4.9 aus über 128 Bewertungen – der Auftritt trägt aber den Namen der Agentur statt der eigenen Firma.",
    paket="Website Business", preis=2790,
    agents="Google-Bewertungen-AI-Agent; SEO",
    agentbegr="Google-Bewertungen-AI-Agent – 4.9 aus 128+ Bewertungen ist eine ausgezeichnete Basis, die konsequent beantwortet und weiter ausgebaut werden sollte. SEO – internationale Umzüge mit Zollabwicklung sind hochwertige Suchbegriffe ohne eigene Landingpage.",
    upsell=1, reputation="4.9 von 5 Sternen bei über 128 verifizierten Kundenbewertungen sowie ASTAG-Mitgliedschaft auf der Website ausgewiesen.",
    aufhaenger="Im Fuss Ihrer Website steht '© 2026 Somion' statt Ihres eigenen Firmennamens – bei 4.9 Sternen aus über 128 Bewertungen ist das schade um die Marke.",
    b_web=2, b_pot=3, b_err=1, b_ag=1)

add(name="La Glaneuse – Umzüge und Brocki (Gemeinnützige Gesellschaft Biel GGB)", vn="Jasna", nn="Röösli", pos="Betriebsleiterin",
    ort="Biel/Bienne", adresse="Obergasse 13, 2502 Biel/Bienne",
    tel="032 322 10 43", teldirekt="Nicht gefunden", mail="info@laglaneuse.ch", web="https://www.ggb-supb.ch/de/umzug-biel/",
    qentscheider="Newsbereich der Organisationswebsite ggb-supb.ch (Betriebsleiterin seit 2013)",
    qkontakt="Website ggb-supb.ch, search.ch, local.ch",
    services="Umzüge, Wohnungsräumungen, Reinigung, Ein- und Auspackservice, Gratis-Abholung von Gegenständen, Einlagerung, Reparaturwerkstatt, Änderungsschneiderei",
    ws=6,
    schwaechen="Copyright-Angabe 2020 – der Auftritt wirkt seit über vier Jahren nicht aktualisiert; auf der Umzugsseite fehlt die vollständige Strassenadresse; die Umzugsdienstleistung ist tief in eine Organisationswebsite eingebettet statt eigenständig positioniert; kein eigener Umzugs-Domainauftritt",
    chance="Etablierte Institution mit über 130 Jahren Geschichte, deren kommerzielle Umzugsdienstleistung in einer Vereinswebsite untergeht.",
    paket="Website Business", preis=2790,
    agents="SEO; Funnel",
    agentbegr="SEO – die Umzugsdienstleistung ist in einer Organisationswebsite vergraben und rankt deshalb nicht für 'Umzugsfirma Biel'. Funnel – die Offertenanfrage ist vorhanden, aber nicht als eigenständige, zweisprachige Conversion-Strecke aufgebaut.",
    upsell=1, reputation="Kunden werden zur Google-Bewertung aufgefordert; Team- und Preisangaben transparent dargestellt.",
    aufhaenger="Ihre Umzugsdienstleistung ist auf einer Vereinsseite vergraben, deren Fuss noch 2020 ausweist – als eigenständiger Auftritt wäre sie in Biel viel sichtbarer.",
    b_web=2, b_pot=3, b_err=1, b_ag=1)

